const en = {
  bonusDictionary: {
    filter: "Filter",
    grade: "Grade",
    bonus: "Bonus",
    createdbyMe:"Created By Me",
    list:"List",
    table:"Table",
    percent:"Percent",
    type:"Type",
    netSalary:"Net Salary",
    selectApprovers: "Select Approvers",
    promotion: "Promotion",
    create: "Create",
    upload: "Upload",
    tableView: "Table View",
    listView: "List View",
    selectMember: "Select Members",
    members: "Members",
    category: "Category",
    approvers: "Approvers",
    bonusTo: "Bonus To",
    myWarning: "My Warning",
    bonusToMe: "Bonus To Me",
    createBonus: "Create Bonus",
    forApproval: "For Approval",
    deductionPerMonth: "Deduction/Months",
    pleaseEnterloanTenureInMonths: "Please enter loan tenure",
    amount: "Amount",
    pleaseEnterAmount: "Please enter amount",
    purpose: "Purpose",
    selectPurpose: "Select purpose",
    deadline: "Deadline",
    description: "Description",
    enterDescription: "Enter Description",
    loanPurpose: {
      vehicle: "Vehicle",
      personal: "Personal",
      wedding: "Wedding",
      medical: "Medical",
      education: "Education",
      house: "House",
      other: "Other",
    },
    tables: {
      sort:"sort",
			ReferenceNum:"Reference Number",
      Creator:"Creator",
      Status:"Status",
      amount:"Amount",
      bonusTo:"Bonus To",
      Date:"Date",
      Approvers:"Approvers",
		},
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default en;
