const en = {
  bonusDictionary: {
    filter: "Filter",
    grade: "Grade",
    bonus: "Bonus",
    selectApprovers: "Select Approvers",
    promotion: "Promotion",
    create: "Create",
    upload: "Upload",
    tableView: "Table View",
    listView: "List View",
    selectMember: "Select Members",
    members: "Members",
    category: "Category",
    approvers: "Approvers",
    bonusTo: "Bonus To",
    myWarning: "My Warning",
    warningToMe: "Warning To Me",
    createBonus: "Create Bonus",
    forApproval: "For Approval",
    deductionPerMonth: "Deduction/Months",
    pleaseEnterloanTenureInMonths: "Please enter loan tenure",
    amount: "Amount",
    pleaseEnterAmount: "Please enter amount",
    purpose: "Purpose",
    selectPurpose: "Select purpose",
    deadline: "Deadline",
    description: "Description",
    enterDescription: "Enter Description",
    loanPurpose: {
      vehicle: "Vehicle",
      personal: "Personal",
      wedding: "Wedding",
      medical: "Medical",
      education: "Education",
      house: "House",
      other: "Other",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default en;
