const hindi = {
  bonusDictionary: {
    filter: "फ़िल्टर",
    grade: "श्रेणी",
    bonus: "बक्शीश",
    selectApprovers: "स्वीकृतकर्ताओं का चयन करें",
    promotion: "पदोन्नति",
    create: "सृजन करना",
    upload: "डालना",
    tableView: "टेबल व्यू",
    listView: "लिस्ट व्यू",
    selectMember: "सदस्यों का चयन करें",
    members: "सदस्यों",
    category: "श्रेणी",
    approvers: "अनुमोदक",
    bonusTo: "बोनस टू",
    myWarning: "मेरी चेतावनी",
    warningToMe: "मुझे चेतावनी",
    createBonus: "बोनस बनाएं",
    forApproval: "अप्रूवल के लिए",
    deductionPerMonth: "कटौती / महीने",
    pleaseEnterloanTenureInMonths: "कृपया ऋण अवधि दर्ज करें",
    amount: "राशि",
    pleaseEnterAmount: "कृपया राशि दर्ज करें",
    purpose: "उद्देश्य",
    selectPurpose: "उद्देश्य चुनें",
    deadline: "समयसीमा",
    description: "विवरण",
    enterDescription: "विवरण दर्ज करें",
    loanPurpose: {
      vehicle: "वाहन",
      personal: "निजी",
      wedding: "शादी",
      medical: "चिकित्सा",
      education: "शिक्षा",
      house: "मकान",
      other: "अन्य",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default hindi;
