const turkish = {
  bonusDictionary: {
    filter: "Filtre",
    grade: "Not",
    bonus: "Bonus",
    selectApprovers: "Onaylayanları Seçin",
    promotion: "Promosyon",
    create: "Oluştur",
    upload: "Yükle",
    tableView: "Tablo Görünümü",
    listView: "Liste Görünümü",
    selectMember: "Üyeleri Seçin",
    members: "Not0",
    category: "Not1",
    approvers: "Not2",
    bonusTo: "Not3",
    myWarning: "Not4",
    warningToMe: "Not5",
    createBonus: "Not6",
    forApproval: "Not7",
    deductionPerMonth: "Not8",
    pleaseEnterloanTenureInMonths: "Not9",
    amount: "Bonus0",
    pleaseEnterAmount: "Bonus1",
    purpose: "Bonus2",
    selectPurpose: "Bonus3",
    deadline: "Bonus4",
    description: "Bonus5",
    enterDescription: "Bonus6",
    loanPurpose: {
      vehicle: "Bonus7",
      personal: "Bonus8",
      wedding: "Bonus9",
      medical: "Onaylayanları Seçin0",
      education: "Onaylayanları Seçin1",
      house: "Onaylayanları Seçin2",
      other: "Onaylayanları Seçin3",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default turkish;
