const urdu = {
  bonusDictionary: {
    filter: "فلٹر",
    selectApprovers: "منظور کنندگان کو منتخب کریں۔",
    promotion: "افروغ",
    createdbyMe:"میرے ذریعہ تخلیق کردہ",
    bonus: "اضافی انعام",
    create: "بنانا",
    grade: "گریڈ",
    list:"فہرست",
    table:"ٹیبل",
    percent:"فیصد",
    type:"قسم",
    netSalary:"خالص تنخواہ",
    upload: "اپ لوڈ",
    tableView: "میز کا منظر",
    listView: "فہرست دیکھیں",
    selectMember: "ممبر کو منتخب کریں۔",
    members: "اراکین",
    category: "قسم",
    approvers: "منظوری دینے والے",
    bonusTo: "کو بونس",
    myWarning: "میرا انتباہ",
    bonusToMe: "مجھے بونس",
    createBonus: "بونس بنائیں",
    forApproval: "منظوری کے لیے",
    deductionPerMonth: "مہینے/کٹوتی",
    pleaseEnterloanTenureInMonths: "براہ کرم قرض کی مدت درج کریں",
    amount: "رقم",
    pleaseEnterAmount: "براہ کرم رقم درج کریں",
    deadline: "ڈیڈ لائن",
    purpose: "مقصد",
    selectPurpose: "مقصد منتخب کریں",
    description: "تفصیل",
    enterDescription: "تفصیل درج کریں",
    loanPurpose: {
      vehicle: "گاڑی",
      personal: "ذاتی",
      wedding: "شادی",
      medical: "طبی",
      education: "تعلیم",
      house: "گھر",
      other: "دوسرے",
    },
    tables: {
      sort:"ترتیب دیں",
			ReferenceNum:"حوالہ نمبر",
      Creator:"خالق",
      Status:"حالت",
      bonusTo:" بونس ٹو",
      amount:"رقم",
      Date:"تاریخ",
      Approvers:"منظور کرنے والے",
		},
  },
  /*** Define language write side ***/
  Direction: "rtl",
};
export default urdu;
