const en = {

	requisitionDictionary: {
		createRequisition: "Create Requisition",
		Requisitions: "Requisitions",
		MyRequisitions: "My Requisitions",
		PleaseEnterRequisitionName: "Please Enter Requisition Name",
		EnterRequisitionName: "Enter Requisition Name",
		Budget: "Budget",
		EnterBudget: "Enter Budget",
		EnterReason: "Enter Reason",
		PleaseSelectApprover: "Please Select Approver",
		FinalApprovers: "Final Approvers",
		PleaseSelectFinalApprovers: "Please Select Final Approvers",
		detail: "Detail",
		CreateOffer: "Create Offer",
		CreatedBy: "Created By",
		Email: "Email",
		PleaseEnterEmail: "Plase Enter Email",
		PleaseEnterPhoneNumber: "Plase Enter Phone Number",
		PleaseEnterBusinessName: "Plase Enter Busimess Name",
		PleaseEnterBusinessAddress: "Plase Enter Busimess Address",
		PleaseEnterOffer: "Plase Enter Offer",
		Offers: "Offers",
		ShortList: "Short List",
		Declined: "Declined",
		Finalised: "inalised",
		PhoneNumber: "Phone Number",
		Offer: "Offer",
		BusinessName: "Business Name",
		BusinessAddress: "Business Address",
		Status: "Status",
		CreateOffer: "Create Offer",
		AppliedDate: "Applied Date",


		enterRewardName: "Entet Reward Name",
		pleaseEnterRewardName: "Please Enter Reward Name",
		enterRewardReason: "Enter Reward Reason",
		reason: "Reason",
		name: "Name",
		filter: "Filter",
		tableView: "Table View",
		listView: "List View",
		complainOf: "Complain Of",
		selectApprovers: "Select Approvers",
		reward: "Reward",
		create: "Create",
		upload: "Upload",
		selectMember: "Select Members",
		members: "Members",
		category: "Category",
		approvers: "Approvers",
		forApproval:"For Approval",
		selectPurpose:"Select purpose",
		deadline:"Deadline",
		description:"Description",
		enterDescription: "Enter Description",
	},

	/*** Define language write side ***/
	Direction: "ltr",
};
export default en;
