const urdu = {

	requisitionDictionary: {
		createRequisition: "ریکوزیشن بنائیں",
		Requisitions: "ریکوزیشن",
		MyRequisitions: "میری درخواست",
		PleaseEnterRequisitionName: "برائے مہربانی درخواست کا نام درج کریں۔",
		EnterRequisitionName: "درخواست کا نام درج کریں۔",
		enterRewardName: "انعام کا نام درج کریں",
		Budget: "بجٹ",
		EnterBudget: "بجٹ درج کریں۔",
		EnterReason: "وجہ درج کریں۔",
		PleaseSelectApprover: "براہ کرم منظور کنندہ کو منتخب کریں۔",
		FinalApprovers: "حتمی منظوری دینے والے",
		PleaseSelectFinalApprovers: "براہ کرم حتمی منظور کنندگان کو منتخب کریں۔",
		detail: "تفصیل",
		CreateOffer: "پیشکش بنائیں",
		CreatedBy: "بنائی گئی",
		Email: "ای میل",
		Offers: "پیشکش کرتا ہے",
		ShortList: "مختصر فہرست",
		Declined: "انکار کر دیا",
		Finalised: "حتمی شکل دی",
		PhoneNumber: "فون نمبر",
		Offer: "پیشکش",
		BusinessName: "کاروبار کا نام",
		BusinessAddress: "کاروباری پتہ",
		Status: "حالت",
		PleaseEnterEmail: "براہ کرم ای میل درج کریں۔",
		PleaseEnterPhoneNumber: "براہ کرم فون نمبر درج کریں۔",
		PleaseEnterBusinessName: "براہ کرم کاروبار کا نام درج کریں۔",
		PleaseEnterBusinessAddress: "براہ کرم کاروباری پتہ درج کریں۔",
		PleaseEnterOffer: "برائے مہربانی پیشکش درج کریں۔",
		CreateOffer: "پیشکش بنائیں",
		AppliedDate: "درخواست کی تاریخ",

		pleaseEnterRewardName: "برائے مہربانی انعام کا نام درج کریں۔",
		enterRewardReason: "انعام کی وجہ درج کریں",
		reason: "وجہ",
		name: "نام",
		filter: "فلٹر",
		tableView: "میز کا منظر",
		listView: "فہرست دیکھیں",
		complainOf: "کی شکایت",
		selectApprovers: "منظور کنندگان کو منتخب کریں۔",
		reward: "انعام",
		create: "بنانا",
		upload: "اپ لوڈ",
		selectMember: "ممبر کو منتخب کریں۔",
		members: "اراکین",
		category: "قسم",
		approvers: "منظوری دینے والے",
		rewardTo: "کو انعام",
		myComplain: "میری شکایت",
		complainToMe: "مجھ سے شکایت",
		createReward: "اجر پیدا کریں",
		forApproval:"منظوری کے لیے",
		deductionPerMonth:"مہینے/کٹوتی",
		pleaseEnterloanTenureInMonths:"براہ کرم قرض کی مدت درج کریں",
		amount:"رقم",
		pleaseEnterAmount:"براہ کرم رقم درج کریں",
		deadline:"ڈیڈ لائن",
		purpose:"مقصد",
		selectPurpose:"مقصد منتخب کریں",
		description:"تفصیل",
		enterDescription: "تفصیل درج کریں",
		loanPurpose:{
			vehicle:"گاڑی",
			personal:"ذاتی",
			wedding:"شادی",
			medical:"طبی",
			education:"تعلیم",
			house:"گھر",
			other:"دوسرے"
		}
	},
	/*** Define language write side ***/
	Direction: "rtl",
};
export default urdu;
