const arabic = {
  complainDictionary: {
    filter: "فلٹر",
    tableView: "میز کا منظر",
    listView: "فہرست دیکھیں",
    complainOf: "کی شکایت",
    selectApprovers: "منظور کنندگان کو منتخب کریں۔",
    complain: "شکایت",
    create: "بنانا",
    upload: "اپ لوڈ",
    selectMember: "ممبر کو منتخب کریں۔",
    members: "اراکین",
    category: "قسم",
    approvers: "منظوری دینے والے",
    warningTo: "کو انتباہ",
    myComplain: "میری شکایت",
    complainToMe: "مجھ سے شکایت",
    createComplain: "شکایت بنائیں",
    forApproval: "منظوری کے لیے",
    deductionPerMonth: "مہینے/کٹوتی",
    pleaseEnterloanTenureInMonths: "براہ کرم قرض کی مدت درج کریں",
    amount: "رقم",
    pleaseEnterAmount: "براہ کرم رقم درج کریں",
    deadline: "ڈیڈ لائن",
    purpose: "مقصد",
    selectPurpose: "مقصد منتخب کریں",
    description: "تفصیل",
    enterDescription: "تفصیل درج کریں",
    loanPurpose: {
      vehicle: "گاڑی",
      personal: "ذاتی",
      wedding: "شادی",
      medical: "طبی",
      education: "تعلیم",
      house: "گھر",
      other: "دوسرے",
    },
  },
  /*** Define language write side ***/
  Direction: "rtl",
};
export default arabic;
