const en = {
  complainDictionary: {
    filter: "Filter",
    tableView: "Table View",
    listView: "List View",
    complainOf: "Complain Of",
    selectApprovers: "Select Approvers",
    complain: "Complain",
    create: "Create",
    upload: "Upload",
    selectMember: "Select Members",
    members: "Members",
    category: "Category",
    approvers: "Approvers",
    warningTo: "Warning To",
    myComplain: "My Complain",
    complainToMe: "Complain To Me",
    createComplain: "Create Complain",
    forApproval: "For Approval",
    deductionPerMonth: "Deduction/Months",
    pleaseEnterloanTenureInMonths: "Please enter loan tenure",
    amount: "Amount",
    pleaseEnterAmount: "Please enter amount",
    purpose: "Purpose",
    selectPurpose: "Select purpose",
    deadline: "Deadline",
    description: "Description",
    enterDescription: "Enter Description",
    Complains: "Complains",
    createdByMe: "Created By Me",
    forApproval: "For Approval",
    complainToMe: "Complain To Me",
    list: "List",
    table: "Table",
    approvals: "Approvals",
    referenceNo: "Reference No",
    creator: "Creator",
    status: "Status",
    date: "Date",
    approvers: "Approvers",
    complaincategory: "Complain Category",
    name: "Name",
    enterCategoryName: "Enter Category Name",
    saveCategory: "Save Category",
    addCategory: "Add Category",
    clear: "Clear",
    loanPurpose: {
      vehicle: "Vehicle",
      personal: "Personal",
      wedding: "Wedding",
      medical: "Medical",
      education: "Education",
      house: "House",
      other: "Other",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default en;
