const hindi = {
  complainDictionary: {
    filter: "फिल्टर",
    tableView: "टेबल व्यू",
    listView: "लिस्ट व्यू",
    complainOf: "शिकायत करें",
    selectApprovers: "स्वीकृतकर्ताओं का चयन करें",
    complain: "शिकायत करना",
    create: "सृजन करना",
    upload: "डालना",
    selectMember: "सदस्यों का चयन करें",
    members: "सदस्यों",
    category: "श्रेणी",
    approvers: "अनुमोदक",
    warningTo: "को चेतावनी",
    myComplain: "मेरी शिकायत",
    complainToMe: "मुझसे शिकायत करें",
    createComplain: "शिकायत बनाएं",
    forApproval: "अप्रूवल के लिए",
    deductionPerMonth: "कटौती / महीने",
    pleaseEnterloanTenureInMonths: "कृपया ऋण अवधि दर्ज करें",
    amount: "राशि",
    pleaseEnterAmount: "कृपया राशि दर्ज करें",
    purpose: "उद्देश्य",
    selectPurpose: "उद्देश्य चुनें",
    deadline: "समयसीमा",
    description: "विवरण",
    enterDescription: "विवरण दर्ज करें",
    loanPurpose: {
      vehicle: "वाहन",
      personal: "निजी",
      wedding: "शादी",
      medical: "चिकित्सा",
      education: "शिक्षा",
      house: "मकान",
      other: "अन्य",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default hindi;
