const en = {
  appraisalDictionary: {
    Appraisals: "Appraisals",
    createAppraisals: "Create Appraisals",
    teamAppraisals: "Team Appraisals",
    myAppraisals: "My Appraisals",
    allAppraisals: "All Appraisals",
    forApprovals: "For Approvals",
    viewAppraisals: "View Appraisals",
    Employee: "Employee",
    startDate: "Start Date",
    endDate: "End Date",
    task: "Task",
    Promotion: "Promotion",
    basicSalary: "Basic Salary",
    previousApraisals: "Previous Appraisals",
    warning: "Warning",
    rewards: "Rewards",
    courses: "Courses",
    yes: "Yes",
    no: "No",
    Bonus: "Bonus",
    increment: "Increment",
    approvers: "Approvers",
    rate: "Rate",
    comment: "Comments",
    currentGrade: "Current Grade",
    assistantManager: "Assistant Manager",
    developers: "Developers",
    executive: "Executive",
    intern: "Intern",
    manager: "Manager",
    officer: "Officer",
    selectApprovers: "Select Approvers",
    percentage: "Percentage",
    amount: "Amount",
    Increment: "Increment",
    comments: "Comments",
    selectGrade: "Select Grade",
    appraisedBy: "APPRAISED BY",
    createdDate: "Created Date",
    STARTDATE: "START DATE",
    ENDDATE: "END DATE",
    PROMOTION: "PROMOTION",
    BONUS: "BONUS",
    INCREMENT: "INCREMENT",
    COMMENT: "COMMENT",
    question: "Questions",
    approvals: "Approvals",
    submitAppraisal: "Submit Appraisals",
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default en;
