const urdu = {
  appraisalDictionary: {
    Appraisals: "تشخیص",
    createAppraisals: "تشخیصات بنائیں",
    teamAppraisals: "ٹیم کی تشخیص",
    myAppraisals: "میری تشخیص",
    forApprovals: "منظوریوں کے لیے",
    viewAppraisals: "تشخیصات دیکھیں",
    Employee: "ملازم",
    startDate: "شروع کرنے کی تاریخ",
    endDate: "آخری تاریخ",
    task: "کام",
    Promotion: "پروموشن",
    basicSalary: "بنیادی تنخواہ",
    previousApraisals: "گزشتہ تشخیص",
    warning: "وارننگ",
    rewards: "انعامات",
    courses: "کورسز",
    yes: "ہاں",
    no: "نہیں",
    Bonus: "اضافی انعام",
    increment: "اضافہ",
    approvers: "منظور کرنے والے",
    rate: "شرح",
    comment: "تبصرے",
    currentGrade: "موجودہ گریڈ",
    assistantManager: "اسسٹنٹ منیجر",
    developers: "ڈویلپرز",
    executive: "ایگزیکٹو",
    intern: "انٹرن",
    manager: "مینیجر",
    officer: "افسر",
    selectApprovers: "منظور کنندگان کو منتخب کریں",
    percentage: "فیصد",
    amount: "رقم",
    Increment: "اضافہ",
    comments: "تبصرے",
    selectGrade: "گریڈ منتخب کریں",
    appraisedBy: "کی طرف سے تشخیص",
    createdDate: "تشکیل کی تاریخ",

    STARTDATE: "شروع کرنے کی تاریخ",
    ENDDATE: "آخری تاریخ",
    PROMOTION: "پروموشن",
    BONUS: "اضافی انعام",
    INCREMENT: "انکریمنٹ",
    COMMENT: "تبصرہ کریں",
    question: "سوالات",
    approvals: "منظوری",
    submitAppraisal: "تشخیص جمع کروائیں",
  },

  /*** Define language write side ***/
  Direction: "rtl",
};
export default urdu;
