const arabic = {
	TravelDictionaryList: {
		createTextBtn: "إنشاء السفر",
		travels: "يسافر",
		topBar: {
			search: "يبحث",
			filter: "منقي",
			list: "قائمة",
			table: "الطاولة",
			travels: "يسافر",
			approval: "للموافقة",
			agentProcess: "عملية الوكيل",
		},

		placeHolder: {
			subjectPh: "أدخل موضوع السفر",
			DescPh: "أدخل وصف السفر",
			approversPh: "البحث عن الموافقين للتحديد",
			agentPh: "وكلاء البحث للاختيار",
			reasonPh: "اكتب سبب السفر",
			traveDepartlPh: "السفر من",
			travelDestPh: "مسافر الى",
			specialRequestPh: "اكتب تفاصيل طلب خاص",
		},
		headings: {
			description: "وصف",
			type: "يكتب",
			project: "مشروع",
			members: "أعضاء",
			approvers: "الموافقون",
			agents: "عملاء",
			desctination: "الأماكن",
		},

		labels: {
			update: "تحديث",
			createTravel: "إنشاء نفقات السفر",
			updateGrp: "تحديث مصاريف السفر",
			subject: "موضوعات",
			description: "وصف",
			approvers: "الموافقون",
			agent: "وكيل",
			reason: "سبب",
			travel: "يسافر",
			date: "تاريخ",
			return: "يعود",
			hotelTada: "فندق وتادا",
			hotelReq: "مطلوب فندق",
			tadaReq: "TADA مطلوبة",
			travelBy: "يسافر بواسطة",
			specialRequest: "طلب خاص",
			attachments: "المرفقات",
			upload: "تحميل",
			add: "يضيف",
			createExpense: "إنشاء حساب",
		},
		travelBy: {
			plane: "بالطائرة",
			bus: "بواسطة الباص",
			ship: "بالسفينة",
			train: "بالقطار",
		},
		table: {
			sort: "فرز",
			reffNo: "رقم المرجع",
			status: "حالة",
			subject: "موضوعات",
			description: "وصف",
			agentStatus: "حالة الوكيل",
			actions: "أجراءات",
			createDate: "تاريخ الإنشاء",
		},
	},
	Direction: "rtl",
};
export default arabic;
