const hindi = {
	TravelDictionaryList: {
		createTextBtn: "Create Travelयात्रा बनाएँ",
		travels: "ट्रेवल्स",
		topBar: {
			search: "खोज",
			filter: "फ़िल्टर",
			list: "सूची",
			table: "मेज",
			travels: "ट्रेवल्स",
			approval: "अप्रूवल के लिए",
			agentProcess: "एजेंट प्रक्रिया",
		},
		placeHolder: {
			subjectPh: "यात्रा विषय दर्ज करें",
			DescPh: "यात्रा विवरण दर्ज करें",
			approversPh: "चुनने के लिए अनुमोदक खोजें",
			agentPh: "चयन करने के लिए एजेंट खोजें",
			reasonPh: "यात्रा का कारण लिखें",
			traveDepartlPh: "तुम कहां से यात्रा कर रहे हो?",
			travelDestPh: "कहाँ जाना है",
			specialRequestPh: "विशेष अनुरोध विवरण लिखें",
		},
		headings: {
			description: "विवरण",
			type: "टाइप",
			project: "परियोजना",
			members: "सदस्यों",
			approvers: "अनुमोदक",
			agents: "एजेंटों",
			desctination: "स्थल",
		},

		labels: {
			update: "अद्यतन",
			createTravel: "यात्रा व्यय बनाएँ",
			updateGrp: "यात्रा व्यय अपडेट करें",
			subject: "विषय",
			description: "विवरण",
			approvers: "अनुमोदक",
			agent: "प्रतिनिधि",
			reason: "कारण",
			travel: "यात्रा करना",
			date: "दिनांक",
			return: "वापस करना",
			hotelTada: "होटल और टाडा",
			hotelReq: "होटल आवश्यक",
			tadaReq: "टाडा आवश्यक",
			travelBy: "यात्रा द्वारा",
			specialRequest: "विशेष अनुरोध",
			attachments: "संलग्नक",
			upload: "डालना",
			add: "जोड़ें",
			createExpense: "व्यय बनाएँ",
		},
		travelBy: {
			plane: "हवाई जहाज से",
			bus: "बस से",
			ship: "जहाज से",
			train: "ट्रेन से",
		},
		table: {
			sort: "क्रम से लगाना",
			reffNo: "संदर्भ संक्या",
			status: "दर्जा",
			subject: "विषय",
			description: "विवरण",
			agentStatus: "एजेंट की स्थिति",
			actions: "कार्रवाई",
			createDate: "तिथि बनाएं",
		},
	},
	Direction: "ltr",
};
export default hindi;
