const turkish = {
	TravelDictionaryList: {
		createTextBtn: "Seyahat Oluştur",
		travels: "seyahatler",
		topBar: {
			search: "Arama",
			filter: "Filtre",
			list: "Liste",
			table: "Masa",
			travels: "seyahatler",
			approval: "Onay için",
			agentProcess: "Temsilci Süreci",
		},
		placeHolder: {
			subjectPh: "Seyahat konusunu girin",
			DescPh: "Seyahat açıklamasını girin",
			approversPh: "Seçmek için onaylayanları arayın",
			agentPh: "Seçilecek aracıları arayın",
			reasonPh: "seyahat sebebini yaz",
			traveDepartlPh: "itibaren seyahat",
			travelDestPh: "seyahat etmek",
			specialRequestPh: "Özel istek detayını yazın",
		},
		headings: {
			description: "Tanım",
			type: "Tip",
			project: "Proje",
			members: "Üyeler",
			approvers: "onaylayanlar",
			agents: "Temsilciler",
			desctination: "Hedefler",
		},

		labels: {
			update: "Güncelleme",
			createTravel: "Seyahat Gideri Yaratın",
			updateGrp: "Seyahat Giderini Güncelle",
			subject: "Ders",
			description: "Tanım",
			approvers: "onaylayanlar",
			agent: "Ajan",
			reason: "Sebep",
			travel: "Yolculuk",
			date: "Tarih",
			return: "Dönüş",
			hotelTada: "Otel ve Tada",
			hotelReq: "Otel Gerekli",
			tadaReq: "TADA Gerekli",
			travelBy: "Tarafından seyahat",
			specialRequest: "Özel istek",
			attachments: "ekler",
			upload: "Yüklemek",
			add: "Ekle",
			createExpense: "Gider Oluştur",
		},
		travelBy: {
			plane: "Uçakla",
			bus: "Otobüs ile",
			ship: "Gemi ile",
			train: "Trenle",
		},
		table: {
			sort: "Çeşit",
			reffNo: "Referans Numarası",
			status: "Durum",
			subject: "Ders",
			description: "Tanım",
			agentStatus: "Temsilci Durumu",
			actions: "Hareketler",
			createDate: "Oluşturma Tarihi",
		},
	},
	Direction: "ltr",
};
export default turkish;
