const turkish = {
	TravelDictionaryList: {
		createTextBtn: "Create Travel",
		travels: "Travels",
		topBar: {
			search: "Search",
			filter: "Filter",
			list: "List",
			table: "Table",
			travels: "Travels",
			approval: "For Approval",
			agentProcess: "Agent Process",
		},
		composer: {
			createTravel: "Create Travel Expense",
		},
		placeHolder: {
			subjectPh: "Enter travel subject",
			DescPh: "Enter travel description",
			approversPh: "Search approvers to select",
			agentPh: "Search agents to select",
			reasonPh: "Write reason of travel",
			traveDepartlPh: "Search departure to select",
			travelDestPh: "Search desctination to select",
			specialRequestPh: "Write special request detail",
		},
		headings: {
			description: "Description",
			type: "Type",
			project: "Project",
			members: "Members",
			approvers: "Approvers",
			agents: "Agents",
			desctination: "Destinations",
		},

		labels: {
			update: "Update",
			createTravel: "Create Travel Expense",
			updateGrp: "Update Travel Expense",
			subject: "Subject",
			description: "Description",
			approvers: "Approvers",
			agent: "Agent",
			reason: "Reason",
			travel: "Travel",
			date: "Date",
			return: "Return",
			hotelTada: "Hotel & Tada",
			hotelReq: "Hotel Required",
			tadaReq: "Tada Required",
			travelBy: "Travel By",
			specialRequest: "Special Request",
			attachments: "Attachments",
			upload: "Upload",
			add: "Add",
			createExpense: "Create Expense",
		},
		travelBy: {
			plane: "By Plane",
			bus: "By Bus",
			ship: "By Ship",
			train: "By Train",
		},
		table: {
			sort: "Sort",
			reffNo: "Refference No",
			status: "Status",
			subject: "Subject",
			description: "Description",
			agentStatus: "Agent Status",
			actions: "Actions",
		},
	},
	Direction: "ltr",
};
export default turkish;
