const urdu = {
	TravelDictionaryList: {
		createTextBtn: "سفر بنائیں",
		travels: "سفر کرتا ہے",
		topBar: {
			search: "تلاش کریں",
			filter: "فلٹر",
			list: "فہرست",
			table: "ٹیبل",
			travels: "سفر کرتا ہے",
			approval: "منظوری کے لیے",
			agentProcess: "ایجنٹ کا عمل",
		},
		placeHolder: {
			subjectPh: "سفر کا مضمون درج کریں",
			DescPh: "أدخل وصف السفر",
			approversPh: "منتخب کرنے کے لیے منظور کنندگان کو تلاش کریں",
			agentPh: "منتخب کرنے کے لیے ایجنٹ تلاش کریں",
			reasonPh: "سفر کی وجہ لکھیں",
			traveDepartlPh: "کہاں سے سفر کر رہے ہیں",
			travelDestPh: "کہاں جانا ہے",
			specialRequestPh: "خصوصی درخواست کی تفصیل لکھیں",
		},
		headings: {
			description: "تفصیل",
			type: "قسم",
			project: "پروجیکٹ",
			members: "ممبران",
			approvers: "منظور کرنے والے",
			agents: "ایجنٹس",
			desctination: "منزلیں",
		},

		labels: {
			update: "اپ ڈیٹ",
			createTravel: "سفری اخراجات بنائیں",
			updateGrp: "سفری اخراجات کو اپ ڈیٹ کریں",
			subject: "مضمون",
			description: "تفصیل",
			approvers: "منظور کرنے والے",
			agent: "ایجنٹ",
			reason: "وجہ",
			travel: "سفر",
			date: "تاریخ",
			return: "واپسی",
			hotelTada: "ہوٹل اور ٹاڈا",
			hotelReq: "ہوٹل کی ضرورت ہے",
			tadaReq: "TADA کی ضرورت ہے",
			travelBy: "سے سفر کرنا",
			specialRequest: "خصوصی درخواست",
			attachments: "منسلکات",
			upload: "اپ لوڈ کریں",
			add: "شامل کریں",
			createExpense: "اخراجات بنائیں",
		},
		travelBy: {
			plane: "جہاز کے ذریعے",
			bus: "بس کے ذریعے",
			ship: "جہاز کے ذریعے",
			train: "ٹرین کے ذریعے",
		},
		table: {
			sort: "ترتیب دیں",
			reffNo: "حوالہ نمبر",
			status: "حالت",
			subject: "مضمون",
			description: "تفصیل",
			agentStatus: "ایجنٹ کی حیثیت",
			actions: "اعمال",
		},
	},
	Direction: "rtl",
};
export default urdu;
