const en = {
  projectsDictionary: {
    createTextBtn: 'Create Project',
    updateTextBtn: 'Update Project',
    routeName: 'Projects',

    topBar: {
      search: 'Search',
      filter: 'Filter',
      list: 'List',
      table: 'Table',
    },
    labels: {
      name: "Name",
      desc: "Description",
      upload: "Upload",
      projectDate: "Project Date",
      externals: "External Members",
      public: "Public",
      private: "Private",
      createdBy: "Created By",
      createdAt: "Created At",
      editProject: "Edit Project",
      totalBudget: "Total Budget",
      balance: "Balance",
      spent: "Spent",
      deadline: "Deadline",
      publicProject: "Public Project",
      privateProject: "Private Project",
      travel: "Travel",
      referenceNo: "Reference No",
      category: "Category",
      status: "Status",
      creator: "Creator",
      reason: "Reason",
    },
    placeholders: {
      name: "Enter name",
      desc: "Enter description",
      members: "Search members",
      type: "Select type",
      externals: "Select externals",
      startDate: "Start Date",
      endDate: "End Date",
      externalEmail: "Enter the Email Adresses",
    },
    errors: {
      name: 'Please enter group name.',
      desc: 'Please enter description.',
      members: 'Please select members.',
      type: 'Please select member type.',
      externals: 'Please select externals',
    },
    features: {
      features: 'Features',
      newsFeed: 'News Feed',
      schedule: 'Schedule',
      workBoard: 'Work Board',
      document: 'Document',
      expenses: 'Expenses',
      task: 'Task',
      travel: 'Travel',
    },
  },

  /*** Define language write side ***/
  Direction: 'ltr',
};
export default en;
