const urdu = {
  projectsDictionary: {
    createTextBtn: "پروجیکٹ بنائیں",
    updateTextBtn: "پروجیکٹ کو اپ ڈیٹ کریں",
    topBar: {
      search: "تلاش کریں",
      filter: "فلٹر",
      list: "فہرست",
      table: "ٹیبل",
    },
    labels: {
      name: "نام",
      desc: "تفصیل",
      upload: "اپ لوڈ کریں",
      projectDate: "پروجیکٹ کی تاریخ",
      externals: "بیرونی",
      public: "Public",
      private: "Private",
      createdBy: "بنائی گئی",
      createdAt: "پر تخلیق کیا گیا",
      editProject: "پروجیکٹ میں ترمیم کریں",
      totalBudget: "کل بجٹ",
      balance: "بقیہ",
      spent: "خرچ کیا",
      deadline: "ڈیڈ لائن",
      publicProject: "پبلک پروجیکٹ",
      privateProject: "پرائیویٹ پروجیکٹ",
      travel: "سفر",
      referenceNo: "حوالہ نمبر",
      category: "قسم",
      status: "حالت",
      creator: "خالق",
      reason: "وجہ",
    },
    placeholders: {
      name: "نام درج کریں",
      desc: "تفصیل درج کریں",
      members: "اراکین کو تلاش کریں",
      type: "قسم منتخب کریں",
      externals: "بیرونی منتخب کریں",
      startDate: "شروع کرنے کی تاریخ",
      endDate: "آخری تاریخ",
      externalEmail: "براہ کرم بیرونی اراکین کا ای میل شامل کریں",
    },
    errors: {
      name: "براہ کرم گروپ کا نام درج کریں۔",
      desc: "براہ کرم تفصیل درج کریں۔",
      members: "براہ کرم اراکین کو منتخب کریں۔",
      type: "براہ کرم ممبر کی قسم منتخب کریں۔",
      externals: "براہ کرم بیرونی کو منتخب کریں۔",
    },
    features: {
      features: "خصوصیات",
      newsFeed: "نیوز فیڈ",
      schedule: "شیڈول",
      workBoard: "ورک بورڈ",
      document: "دستاویز",
      task: "کام",
      expenses: "اخراجات",
      travel: "سفر",
    },
  },

  /*** Define language write side ***/
  Direction: "rtl",
};
export default urdu;
