const en = {
  taskDictionaryList: {
    createTextBtn: "Create Task",
    placeHolder: {
      writeSubject: "Write Subject Here",
      writePredecessor: "Write Predecessor Here",
      writeDescription: "Write Description Here",
      startDate: " Start Date",
      endtDate: " Start End",
      selectAssign: "Select Assign",
    },
    labels: {
      taskDetail: "Task Detail",
      attachments: "Attachments",
      taskSubject: "Task Subject",
      predecessor: "Predecessor",
      type: "Type",
      taskDate: "Task Date",
      priority: "Priority",
      group: "Group",
      project: "Project",
      general: "General",
      assignTo: "Assign To",
      assignTask: "Assign Task",
      selfTask: "Self Task",
      high: "High",
      medium: "Medium",
      low: "Low",
      default: "Default",
      checkList: "Check List",
      description: "Description",
      startDate: " Start Date",
      endtDate: " End Date",
      notStarted: "NotStarted",
      inProcess: "InProcess",

      completed: "Completed",
      ratingAssign: "RatingAssign",
      cancelled: "Cancelled",
      referenceNo: "Reference No",
      creator: "Creator",
      status: "Status",
      subject: "Subject",
      progress: "Progress",
      taskAssignedTo: "Task Assigned To",
    },
  },
  Direction: "ltr",
};
export default en;
