const urdu = {
  taskDictionaryList: {
    createTextBtn: "ٹاسک بنائیں",
    placeHolder: {
      writeSubject: "یہاں سبجیکٹ لکھیں",
      writePredecessor: "یہاں پیشرو لکھیں",
      writeDescription: "تفصیل لکھیں۔",
      startDate: "شروع کرنے کی تاریخ",
      endtDate: "شروع اختتام",
      selectAssign: "تفویض کو منتخب کریں",
    },
    labels: {
      taskDetail: "Task Detail",
      attachments: "Attachments",
      taskSubject: "ٹاسک کا موضوع",
      predecessor: "پیشرو",
      type: "قسم",
      taskDate: "ٹاسک کی تاریخ",
      priority: "ترجیح",
      group: "گروپ",
      project: "پروجیکٹ",
      general: "جنرل",
      assignTask: "ٹاسک تفویض کریں۔",
      assignTo: "کو سونپا گیا",
      selfTask: "سیلف ٹاسک",
      high: "اعلی",
      medium: "درمیانہ",
      low: "کم",
      default: "پہلے سے طے شدہ",
      checkList: "چیک لسٹ",
      description: "تفصیل",
      startDate: "شروع کرنے کی تاریخ",
      endtDate: "شروع اختتام",
    },
  },
  Direction: "rtl",
};
export default urdu;
