const arabic = {
	WorkBoardDictionaryList: {
		createTextBtn: "إنشاء لوحة",
		dashboard: "لوحة القيادة",
		topBar: {
			search: "بحث",
			filter: "منقي",
			list: "قائمة",
			table: "الطاولة",
			publicGroup: "مجموعة عامة",
			privateGroup: "مجموعة خاصة",
		},
		labels: {
			update: "تحديث المجلس",
			create: "إنشاء لوحة",
			name: "اسم المجلس",
			description: "وصف المجلس",
			members: "أفراد",
			public: "عام",
			private: "خاص",
			uploadCvr: "تحميل الغلاف",
			addSection: "إضافة قسم",
			enterSectionTitle: "أدخل عنوان القسم",
			addTodo: "أضف Todo",
			delete: "حذف",
			enterTodoTitle: "أدخل عنوان المهام",
			addMembers: "إضافة أعضاء",
			addDate: "إضافة تاريخ",
			inSection: "in section",
			todoDescPlaceholder: "أضف وصفًا أكثر تفصيلاً ..",
			attachments: "المرفقات",
			activity: "نشاط",
			commentPLaceholder: "اكتب تعليقاتك هنا",
			members: "Members",
			label: "مُلصَق",
			checkList: "قائمة تدقيق",
			dates: "تواريخ",
			cover: "التغطية",
			save: "يحفظ",
			cancel: "يلغي",
			dueDate: "تاريخ الاستحقاق",
			tomorrow: "الغد",
			today: "اليوم",
			dueSoon: "قريب",
			overDue: "متأخر",
			completed: "منجز",
			selectDate: "حدد تاريخ",
		},
		placeholder: {
			name: "أدخل اسم اللوحة",
			desc: "أدخل وصف اللوحة",
			members: "أعضاء البحث",
		},

		errors: {
			name: "الرجاء إدخال اسم المجلس!",
			desc: "الرجاء إدخال وصف المجلس!",
		},
	},
	Direction: "rtl",
};
export default arabic;
