const en = {
	WorkBoardDictionaryList: {
		createTextBtn: "إنشاء لوحة",
		dashboard: "Dashboard",
		topBar: {
			search: "Search",
			filter: "Filter",
			list: "List",
			table: "Table",
			publicGroup: "مجموعة عامة",
			privateGroup: "مجموعة خاصة",
		},
		labels: {
			update: "تحديث المجلس",
			create: "إنشاء لوحة",
			name: "Board Name",
			description: "Board Description",
			members: "Members",
			public: "Public",
			private: "Private",
			uploadCvr: "Upload Cover",
		},
		placeholder: {
			name: "Enter board name",
			desc: "Enter board description",
			members: "Search membres",
		},
		update: "Update Board",
		name: "Board Name",
		description: "Board Description",
		members: "Members",
		uploadCover: "Upload Cover",
		public: "public",
		private: "private",

		addSection: "Add Section",
		enterSectionTitle: "Enter Section Title",
		addTodo: "Add Todo",
		delete: "Delete",
		enterTodoTitle: "Enter todo title",
		addMembers: "Add Members",
		addDate: "Add Date",
		inSection: "in section",
		todoDescription: "Description",
		todoDescPlaceholder: "Add more detailed description..",
		attachments: "Attachments",
		activity: "Activity",
		commentPLaceholder: "Write Your Comments Here",
		members: "Members",
		label: "Label",
		checkListL: "Check List",
		dates: "Dates",
		cover: "Cover",
		save: "Save",
		cancel: "Cancel",
		dueDate: "Due date",
		tomorrow: "tomorrow",
		today: "today",
		dueSoon: "due soon",
		overDue: "over due",
		completed: "completed",
		selectDate: "Select Date",
		filter: "Filter",
		list: "List",
		table: "Table",
		search: "Search",
		searchMembers: "Search Members",

		namePlaceholder: "Enter Board Name",
		descriptionPlaceholder: "Enter Board Description",
		memberPlaceholder: "Select Members",
		nameError: "Please Enter Board Name!",
		descriptionError: "Please Enter Board Description!",
	},
	Direction: "ltr",
};
export default en;
