const langauge={
    create:"Create Board",
    dashboard:"Dashboard",
    publicGroup:"Public Group",
    privateGroup:"Private Group",
    update:"Update Board",
    name:"Board Name",
    description:"Board Description",
    members:"Members",
    uploadCover:"Upload Cover",
    public:"public",
    private:"private",

    addSection:"Add Section",
    enterSectionTitle: "Enter Section Title",
    addTodo: "Add Todo",
    delete:'Delete',
    enterTodoTitle:'Enter todo title',
    addMembers:'Add Members',
    addDate: 'Add Date',
    inSection: 'in section',
    todoDescription: 'Description',
    todoDescPlaceholder: 'Add more detailed description..',
    attachments: 'Attachments',
    activity: 'Activity',
    commentPLaceholder:'Write Your Comments Here',
    members:'Members',
    label:'Label',
    checkListL:'Check List',
    dates:'Dates',
    cover:'Cover',
    save:'Save',
    cancel: 'Cancel',
    dueDate:'Due date',
    tomorrow:'tomorrow',
    today:'today',
    dueSoon:'due soon',
    overDue:'over due',
    completed:'completed',
    selectDate: 'Select Date',
    filter:'Filter',
    list:'List',
    table:'Table',
    search:'Search',
    searchMembers: 'Search Members',



    namePlaceholder:"Enter Board Name",
    descriptionPlaceholder:"Enter Board Description",
    memberPlaceholder:"Select Members",
    nameError:"Please Enter Board Name!",
    descriptionError:"Please Enter Board Description!",


}