const en = {
  WorkBoardDictionaryList: {
    createTextBtn: "Create Board",
    dashboard: "Dashboard",
    workBoard: "Workboard Dashboard",
    testingAndroid: "Testing Android",
    topBar: {
      search: "Search",
      filter: "Filter",
      list: "List",
      table: "Table",
      publicGroup: "Public Group",
      privateGroup: "Private Group",
    },
    labels: {
      update: "Update Board",
      create: "Create Board",
      name: "Name",
      description: "Board Description",
      members: "Members",
      public: "Public",
      private: "Private",
      uploadCvr: "Upload Cover",
      addSection: "Add Section",
      enterSectionTitle: "Enter Section Title",
      addTodo: "Add Todo",
      delete: "Delete",
      enterTodoTitle: "Enter todo title",
      addMembers: "Add Members",
      addDate: "Add Date",
      inSection: "in section",
      todoDescription: "Description",
      todoDesc: "Add more detailed description..",
      attachments: "Attachments",
      activity: "Activity",
      comment: "Write Your Comments Here",
      members: "Members",
      label: "Label",
      checkList: "Check List",
      dates: "Dates",
      cover: "Cover",
      save: "Save",
      cancel: "Cancel",
      dueDate: "Due date",
      tomorrow: "tomorrow",
      today: "today",
      dueSoon: "due soon",
      overDue: "over due",
      completed: "completed",
      selectDate: "Select Date",
      filter: "Filter",
      list: "List",
      table: "Table",
      search: "Search",
      searchMembers: "Search Members",
      Update: "Update",
      Create: "Create",
      Board: "Board",
      uploadCoverPhoto: "Upload Cover Photo",
      edit: "Edit",
      addCard: "Add Todo",
      section: "Section",
      title: "Title",
      description: "Description",
      labels: "Labels",
      createdDate: "Created Date",
    },
    placeholder: {
      name: "Enter board name",
      desc: "Enter board description",
      members: "Search members",
      detailedDesc: "Add more detailed description...",
    },

    errors: {
      name: "Please Enter Board Name!",
      desc: "Please Enter Board Description!",
    },
  },
  Direction: "ltr",
};
export default en;
