const hindi = {
	WorkBoardDictionaryList: {
		createTextBtn: "बोर्ड बनाएं",
		dashboard: "डैशबोर्ड",
		topBar: {
			search: "खोज",
			filter: "फ़िल्टर",
			list: "सूची",
			table: "मेज",
			publicGroup: "सार्वजनिक समूह",
			privateGroup: "निजी समूह",
		},
		labels: {
			update: "अद्यतन बोर्ड",
			create: "बोर्ड बनाएं",
			name: "बोर्ड का नाम",
			description: "बोर्ड विवरण",
			members: "समूह विवरण",
			public: "जनता",
			private: "निजी",
			uploadCvr: "कवर अपलोड करें",
			addSection: "अनुभाग जोड़ें",
			enterSectionTitle: "अनुभाग शीर्षक दर्ज करें",
			addTodo: "टूडू जोड़ें",
			delete: "मिटाना",
			enterTodoTitle: "टूडू शीर्षक दर्ज करें",
			addMembers: "सदस्य जोड़ें",
			addDate: "तिथि जोड़ें",
			inSection: "in section",
			todoDescPlaceholder: "अधिक विस्तृत विवरण जोड़ें..",
			attachments: "संलग्नक",
			activity: "गतिविधि",
			commentPLaceholder: "अपनी टिप्पणियाँ यहाँ लिखें",
			members: "Members",
			label: "लेबल",
			checkList: "चेक लिस्ट",
			dates: "पिंड खजूर।",
			cover: "ढकना",
			save: "बचाना",
			cancel: "रद्द करना",
			dueDate: "नियत तारीख",
			tomorrow: "कल",
			today: "आज",
			dueSoon: "जल्द ही देय",
			overDue: "अतिदेय",
			completed: "पूरा किया हुआ",
			selectDate: "तारीख़ चुनें",
		},
		placeholder: {
			name: "बोर्ड का नाम दर्ज करें",
			desc: "बोर्ड विवरण दर्ज करें",
			members: "Search membres",
		},

		errors: {
			name: "कृपया बोर्ड का नाम दर्ज करें!",
			desc: "कृपया बोर्ड विवरण दर्ज करें!",
		},
	},
	Direction: "rtl",
};
export default hindi;
