const turkish = {
	WorkBoardDictionaryList: {
		createTextBtn: "Pano Oluştur",
		dashboard: "Gösterge Paneli",
		topBar: {
			search: "Arama",
			filter: "Filtre",
			list: "Liste",
			table: "Masa",
			publicGroup: "Genel Grup",
			privateGroup: "Özel Grup",
		},
		labels: {
			update: "Panoyu Güncelle",
			create: "Pano Oluştur",
			name: "Kurul adı",
			description: "Yönetim Kurulu Açıklaması",
			members: "Üyeler",
			public: "Halk",
			private: "Özel",
			uploadCvr: "Kapak Yükle",
			addSection: "Bölüm Ekle",
			enterSectionTitle: "Bölüm Başlığını Girin",
			addTodo: "Yapılacakları Ekle",
			delete: "Silmek",
			enterTodoTitle: "Yapılacaklar başlığını girin",
			addMembers: "Üye ekle",
			addDate: "Tarih ekle",
			inSection: "in section",

			attachments: "ekler",
			activity: "Aktivite",

			members: "Members",
			label: "Etiket",
			checkList: "Kontrol Listesi",
			dates: "Tarih",
			cover: "Örtmek",
			save: "Kaydetmek",
			cancel: "İptal",
			dueDate: "Bitiş tarihi",
			tomorrow: "yarın",
			today: "bugün",
			dueSoon: "yakında",
			overDue: "gecikmiş",
			completed: "Tamamlandı",
			selectDate: "Tarih seç",
		},
		placeholder: {
			name: "Pano adını girin",
			desc: "Pano açıklamasını girin",
			members: "Search membres",
			todoDesc: "Daha detaylı açıklama ekleyin..",
			comment: "Yorumlarınızı Buraya Yazın",
		},

		errors: {
			name: "Lütfen Yönetim Kurulu Adını Girin!",
			desc: "Lütfen Pano Açıklamasını Girin!",
		},
	},
	Direction: "ltr",
};
export default turkish;
