const urdu = {
	WorkBoardDictionaryList: {
		createTextBtn: "بورڈ بنائیں",
		dashboard: "Dashboard",
		topBar: {
			search: "تلاش کریں",
			filter: "فلٹر",
			list: "فہرست",
			table: "ٹیبل",
			publicGroup: "عوامی گروپ",
			privateGroup: "پرائیویٹ گروپ",
		},
		labels: {
			update: "اپ ڈیٹ بورڈ",
			create: "بورڈ بنائیں",
			name: "بورڈ کا نام",
			description: "بورڈ کی تفصیل",
			members: "ممبران",
			public: "عوام",
			private: "نجی",
			uploadCvr: "کور اپ لوڈ کریں",
			addSection: "سیکشن شامل کریں",
			enterSectionTitle: "سیکشن کا عنوان درج کریں",
			addTodo: "ٹوڈو شامل کریں",
			delete: "حذف کریں",
			enterTodoTitle: "ٹوڈو کا عنوان درج کریں",
			addMembers: "ممبرز کو شامل کریں",
			addDate: "تاریخ شامل کریں",
			inSection: "in section",
			todoDescPlaceholder: "مزید تفصیلی وضاحت شامل کریں..",
			attachments: "منسلکات",
			activity: "سرگرمی",
			commentPLaceholder: "اپنے تبصرے یہاں لکھیں",
			members: "Members",
			label: "لیبل",
			checkList: "چیک لسٹ",
			dates: "تاریخوں",
			cover: "ڈھانپنا",
			save: "محفوظ کریں",
			cancel: "منسوخ کریں",
			dueDate: "اخری تاریخ",
			tomorrow: "کل",
			today: "آج",
			dueSoon: "جلد ہی واجب الادا",
			overDue: "زائد المیعاد",
			completed: "مکمل",
			selectDate: "تاریخ منتخب کریں",
		},
		placeholder: {
			name: "بورڈ کا نام درج کریں",
			desc: "بورڈ کی تفصیل درج کریں",
			members: "میمبرز تلاش کریں",
		},

		errors: {
			name: "براہ کرم بورڈ کا نام درج کریں!",
			desc: "براہ کرم بورڈ کی تفصیل درج کریں!",
		},
	},
	Direction: "rtl",
};
export default urdu;
