const urdu = {
  WorkBoardDictionaryList: {
    createTextBtn: "بورڈ بنائیں",
    dashboard: "ڈیش بورڈ",
    workBoard: "ورک بورڈ ڈیش بورڈ",
    testingAndroid: "اینڈرائیڈ کی جانچ",
    topBar: {
      search: "تلاش کریں",
      filter: "فلٹر",
      list: "فہرست",
      table: "ٹیبل",
      publicGroup: "عوامی گروپ",
      privateGroup: "پرائیویٹ گروپ",
    },
    labels: {
      update: "اپ ڈیٹ بورڈ",
      create: "بورڈ بنائیں",
      name: "بورڈ کا نام",
      description: "بورڈ کی تفصیل",
      members: "ممبران",
      public: "عوام",
      private: "نجی",
      uploadCvr: "کور اپ لوڈ کریں",
      addSection: "سیکشن شامل کریں",
      enterSectionTitle: "سیکشن کا عنوان درج کریں",
      addTodo: "ٹوڈو شامل کریں",
      delete: "حذف کریں",
      enterTodoTitle: "ٹوڈو کا عنوان درج کریں",
      addMembers: "ممبرز کو شامل کریں",
      addDate: "تاریخ شامل کریں",
      inSection: "in section",
      todoDescription: "تفصیل",

      todoDescPlaceholder: "مزید تفصیلی وضاحت شامل کریں..",
      attachments: "منسلکات",
      activity: "سرگرمی",
      commentPLaceholder: "اپنے تبصرے یہاں لکھیں",
      members: "ممبران",
      label: "لیبل",
      checkList: "چیک لسٹ",
      dates: "تاریخوں",
      cover: "ڈھانپنا",
      save: "محفوظ کریں",
      cancel: "منسوخ کریں",
      dueDate: "اخری تاریخ",
      tomorrow: "کل",
      today: "آج",
      dueSoon: "جلد ہی واجب الادا",
      overDue: "زائد المیعاد",
      completed: "مکمل",
      selectDate: "تاریخ منتخب کریں",
      Update: "اپ ڈیٹ",
      Create: "بنانا",
      Board: "بورڈ",
      uploadCoverPhoto: "کور فوٹو اپ لوڈ کریں",
      edit: "ترمیم",
      addCard: "کارڈ شامل کریں",
      section: "سیکشن",
      title: "عنوان",
      description: "تفصیل",
      labels: "لیبلز",
      createdDate: "تشکیل کی تاریخ",
    },
    placeholder: {
      name: "بورڈ کا نام درج کریں",
      desc: "بورڈ کی تفصیل درج کریں",
      members: "میمبرز تلاش کریں",
      detailedDesc: "مزید تفصیلی وضاحت شامل کریں",
    },

    errors: {
      name: "براہ کرم بورڈ کا نام درج کریں!",
      desc: "براہ کرم بورڈ کی تفصیل درج کریں!",
    },
  },
  Direction: "rtl",
};
export default urdu;
