const en = {
  promotionDictionary: {
    filter: "Filter",
    grade: "Grade",
    createdbyMe:"Created By Me",
    promotion:"Promotions",
    newGrade:"New Grade",
    currentGrades:"current Grades",
    grades:"Grades",
    selectApprovers: "Select Approvers",
    promotion: "Promotion",
    create: "Create",
    upload: "Upload",
    tableView: "Table View",
    listView: "List View",
    list:"List",
    table:"table",
    selectMember: "Select Members",
    members: "Members",
    category: "Category",
    approvers: "Approvers",
    promotionTo: "Promotion To",
    myWarning: "My Promotion",
    promotionToMe: "Promotion To Me",
    createPromotion: "Create Promotion",
    forApproval: "For Approval",
    deductionPerMonth: "Deduction/Months",
    pleaseEnterloanTenureInMonths: "Please enter loan tenure",
    amount: "Amount",
    pleaseEnterAmount: "Please enter amount",
    purpose: "Purpose",
    selectPurpose: "Select purpose",
    deadline: "Deadline",
    description: "Description",
    enterDescription: "Enter Description",
    loanPurpose: {
      vehicle: "Vehicle",
      personal: "Personal",
      wedding: "Wedding",
      medical: "Medical",
      education: "Education",
      house: "House",
      other: "Other",
    },
    tables: {
      sort:"sort",
			ReferenceNum:"Reference Number",
      Creator:"Creator",
      Status:"Status",
      promotionTo:"Promotion To",
      Date:"Date",
      Approvers:"Approvers",
		},
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default en;
