const turkish = {
  promotionDictionary: {
    filter: "Filtre",
    grade: "Derecelendirme",
    selectApprovers: "Onaylayanları Seçin",
    promotion: "Promosyon",
    create: "Oluştur",
    upload: "Yükle",
    tableView: "Tablo Görünümü",
    listView: "Liste Görünümü",
    selectMember: "Üyeleri Seçin",
    members: "Üyeler",
    category: "Derecelendirme0",
    approvers: "Derecelendirme1",
    promotionTo: "Derecelendirme2",
    myWarning: "Derecelendirme3",
    warningToMe: "Derecelendirme4",
    createPromotion: "Derecelendirme5",
    forApproval: "Derecelendirme6",
    deductionPerMonth: "Derecelendirme7",
    pleaseEnterloanTenureInMonths: "Derecelendirme8",
    amount: "Derecelendirme9",
    pleaseEnterAmount: "Onaylayanları Seçin0",
    purpose: "Onaylayanları Seçin1",
    selectPurpose: "Onaylayanları Seçin2",
    deadline: "Onaylayanları Seçin3",
    description: "Onaylayanları Seçin4",
    enterDescription: "Onaylayanları Seçin5",
    loanPurpose: {
      vehicle: "Onaylayanları Seçin6",
      personal: "Onaylayanları Seçin7",
      wedding: "Onaylayanları Seçin8",
      medical: "Onaylayanları Seçin9",
      education: "Promosyon0",
      house: "Promosyon1",
      other: "Promosyon2",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default turkish;
