const urdu = {
  promotionDictionary: {
    filter: "فلٹر",
    selectApprovers: "منظور کنندگان کو منتخب کریں۔",
    promotion: "افروغ",
    createdbyMe:"میری طرف سے پیدا کیا",
    create: "بنانا افروغ",
    grade: "گریڈ",
    newGrade:"نیا گریڈ",
    currentGrades:"موجودہ درجات",
    grades:"درجات",
    upload: "اپ لوڈ",
    tableView: "میز کا منظر",
    listView: "فہرست دیکھیں",
    list:"فہرست",
    table:"ٹیبل",
    selectMember: "ممبر کو منتخب کریں۔",
    members: "اراکین",
    category: "قسم",
    approvers: "منظوری دینے والے",
    promotionTo: "کو فروغ دینا",
    myWarning: "میرا انتباہ",
    promotionToMe: " مجھے پروموشن",
    createPromotion: "فروغ بنائیں",
    forApproval: "منظوری کے لیے",
    deductionPerMonth: "مہینے/کٹوتی",
    pleaseEnterloanTenureInMonths: "براہ کرم قرض کی مدت درج کریں",
    amount: "رقم",
    pleaseEnterAmount: "براہ کرم رقم درج کریں",
    deadline: "ڈیڈ لائن",
    purpose: "مقصد",
    selectPurpose: "مقصد منتخب کریں",
    description: "تفصیل",
    enterDescription: "تفصیل درج کریں",
    loanPurpose: {
      vehicle: "گاڑی",
      personal: "ذاتی",
      wedding: "شادی",
      medical: "طبی",
      education: "تعلیم",
      house: "گھر",
      other: "دوسرے",
    },
    tables: {
      sort:"ترتیب دیں",
			ReferenceNum:"حوالہ نمبر",
      Creator:"خالق",
      Status:"حالت",
      promotionTo:"پروموشن ٹو",
      Date:"تاریخ",
      Approvers:"منظور کرنے والے",
		},
  },
  /*** Define language write side ***/
  Direction: "rtl",
};
export default urdu;
