const hindi = {
  taskDictionaryList: {
    createTextBtn: "टास्क बनाएं",
    placeHolder: {
      writeSubject: "विषय यहाँ लिखें",
      writePredecessor: "पूर्ववर्ती यहाँ लिखें",
      writeDescription: "विवरण यहाँ लिखें",
      startDate: " आरंभ करने की तिथि",
      endtDate: " शुरू अंत",
      selectAssign: "असाइन करें का चयन करें",
    },
    labels: {
      taskSubject: "कार्य विषय",
      predecessor: "पूर्वज",
      type: "टाइप",
      taskDate: "कार्य तिथि",
      priority: "वरीयता",
      group: "समूह",
      project: "परियोजना",
      general: "सामान्य",
      assignTo: "के लिए आवंटित",
      assignTask: "टास्क असाइन करें",
      selfTask: "सेल्फ टास्क",
      high: "उच्च",
      medium: "मध्यम",
      low: "कम",
      default: "चूक",
      checkList: "चेक लिस्ट",
      description: "विवरण",
      startDate: " आरंभ करने की तिथि",
      endtDate: " शुरू अंत",
    },
  },
  Direction: "ltr",
};
export default hindi;
