const en = {
  documentDictionary: {
    forms: "Forms",
    createForms: "Create Form",
    allForms: "All Forms",
    myForms: "My Forms",
    forApprovals: "For Approvals",
    list: "List",
    table: "Table",
    copyLink: "Copy Link",
    attempt: "Attempt",
    Subject: "Subject",
    Description: "Description",
    Approvals: "Approvals",
    title: "Title",
    Approvers: "Approvers",
    Question: "Question...",
    text: "Text",
    number: "Number",
    polls: "Polls",
    addQuestion: "Add Question",
    selectApprovers: "Select Approvers",
    selectAnswerType: "Select Answer Type",
    addOption: "Add Option",
    editForm: "Edit Form",
    email: "Email",
    yourEmail: "Your Email",
    submit: "Submit",
    poweredBy: "Powered By",
    yourAnswer: "Your Answer",
    referenceNo: "Reference No",
    creator: "Creator",
    status: "Status",
    date: "Date",
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default en;
