const urdu = {
  documentDictionary: {
    forms: "فارمز",
    createForms: "فارم بنائیں",
    allForms: "تمام فارمز",
    myForms: "میرے فارم",

    forApprovals: "منظوریوں کے لیے",
    list: "فہرست",
    table: "ٹیبل",
    copyLink: "لنک کاپی کریں",
    attempt: "کوشش",
    Subject: "مضمون",
    Description: "تفصیل",
    Approvals: "منظوری",
    title: "عنوان",
    Approvers: "منظور کرنے والے",
    Question: "سوال",
    text: "متن",
    number: "نمبر",
    polls: "پولز",
    addQuestion: "سوال شامل کریں",
    selectApprovers: "منظور کنندگان کو منتخب کریں",
    selectAnswerType: "جواب کی قسم منتخب کریں",
    addOption: "آپشن شامل کریں",
    editForm: "فارم میں ترمیم کریں",
    email: "ای میل",
    yourEmail: "آپ کا ای میل",
    submit: "جمع کرائیں",
    poweredBy: "کی طرف سے طاقت",
    yourAnswer: "آپ کا جواب",
  },
  /*** Define language write side ***/
  Direction: "rtl",
};
export default urdu;
