const en = {
  profileDictionary: {
    firstMenu: '  1st menu item',
    secondMenu: ' 2nd menu item (disabled)',
    thirdMenu: ' 3rd menu item (disabled)',
    dangerItem: 'a danger item',
    information: 'Information',
    feed: 'Feed',
    about: 'About',
    work: 'Work',
    addWorkPlace: 'Add Work Place',
    studiesALevel: 'Studied A- Levels at',
    designation: 'Designation',
    email: 'Email',
    relationship: 'Relationship',
    livesIn: 'Lives in',
    contact: 'Contact',
    joining: 'Joining',
    birthday: 'BirthDay',
    education: 'Education',
    single: 'Single',
    engaged: 'Engaged',
    married: 'Married',
    divorced: 'Divorced',
    widow: 'Widowed',
    widower: 'Widower',
    preferNotTosay: 'Prefer Not To Say',
    addAEducation: 'Add a education',
    awards: 'Awards',
    appraisal: 'Appraisal',
    salary: 'Salary',
    activityLog: 'Activity Log',
    courses: 'Courses',
    leave: 'Leave',
    experience: 'Experience',
    checkIn: 'Check In',
  },

  /*** Define language write side ***/
  Direction: 'ltr',
};
export default en;
