const en = {
  rewardDictionary: {
    enterRewardName: "Enter Reward Name",
    pleaseEnterRewardName: "Please Enter Reward Name",
    enterRewardReason: "Enter Reward Reason",
    reason: "Reason",
    name: "Name",
    filter: "Filter",
    tableView: "Table View",
    listView: "List View",
    complainOf: "Complain Of",
    selectApprovers: "Select Approvers",
    reward: "Reward",
    rewards: "Rewards",
    create: "Create",
    upload: "Upload",
    selectMember: "Select Members",
    members: "Members",
    category: "Category",
    approvers: "Approvers",
    rewardTo: "Reward To",
    createReward: "Create Reward",
    forApproval: "For Approval",
    deductionPerMonth: "Deduction/Months",
    pleaseEnterloanTenureInMonths: "Please enter loan tenure",
    amount: "Amount",
    pleaseEnterAmount: "Please enter amount",
    purpose: "Purpose",
    selectPurpose: "Select purpose",
    deadline: "Deadline",
    description: "Description",
    enterDescription: "Enter Description",
    createdByMe: "Created By Me",
    rewardToMe: "Reward To Me",
    table: "Table",
    list: "List",
    cancel: "Cancel",
    rewardCategory: "Reward Category",
    enterrewardCategory: "Enter Reward Category",
    selectCategory: "Select Category",
    referenceNo: "Reference No",
    creator: "Creator",
    status: "Status",
    date: "Date",
    addCategory: "Add Category",
    saveCategory: "Save Category",
    clear: "Clear",

    loanPurpose: {
      vehicle: "Vehicle",
      personal: "Personal",
      wedding: "Wedding",
      medical: "Medical",
      education: "Education",
      house: "House",
      other: "Other",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default en;
