const hindi = {
  rewardDictionary: {
    enterRewardName: "एंटेट इनाम का नाम",
    pleaseEnterRewardName: "कृपया इनाम का नाम दर्ज करें",
    enterRewardReason: "इनाम का कारण दर्ज करें",
    reason: "कारण",
    name: "नाम",
    filter: "फ़िल्टर",
    tableView: "तालिका दृश्य",
    listView: "सूची दृश्य",
    complainOf: "शिकायत करें",
    selectApprovers: "अनुमोदकों का चयन करें",
    reward: "कृपया इनाम का नाम दर्ज करें0",
    create: "कृपया इनाम का नाम दर्ज करें1",
    upload: "कृपया इनाम का नाम दर्ज करें2",
    selectMember: "कृपया इनाम का नाम दर्ज करें3",
    members: "कृपया इनाम का नाम दर्ज करें4",
    category: "कृपया इनाम का नाम दर्ज करें5",
    approvers: "कृपया इनाम का नाम दर्ज करें6",
    rewardTo: "कृपया इनाम का नाम दर्ज करें7",
    createReward: "कृपया इनाम का नाम दर्ज करें8",
    forApproval: "कृपया इनाम का नाम दर्ज करें9",
    deductionPerMonth: "इनाम का कारण दर्ज करें0",
    pleaseEnterloanTenureInMonths: "इनाम का कारण दर्ज करें1",
    amount: "इनाम का कारण दर्ज करें2",
    pleaseEnterAmount: "इनाम का कारण दर्ज करें3",
    purpose: "इनाम का कारण दर्ज करें4",
    selectPurpose: "इनाम का कारण दर्ज करें5",
    deadline: "इनाम का कारण दर्ज करें6",
    description: "इनाम का कारण दर्ज करें7",
    enterDescription: "इनाम का कारण दर्ज करें8",
    loanPurpose: {
      vehicle: "इनाम का कारण दर्ज करें9",
      personal: "कारण0",
      wedding: "कारण1",
      medical: "कारण2",
      education: "कारण3",
      house: "कारण4",
      other: "कारण5",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default hindi;
