const turkish = {
  rewardDictionary: {
    enterRewardName: "Ödül Adını Girin",
    pleaseEnterRewardName: "Lütfen Ödül Adını Girin",
    enterRewardReason: "Ödül Nedenini Girin",
    reason: "Neden",
    name: "Ad",
    filter: "Filtre",
    tableView: "Tablo Görünümü",
    listView: "Liste Görünümü",
    complainOf: "Şikayet Et",
    selectApprovers: "Onaylayıcıları Seçin",
    reward: "Lütfen Ödül Adını Girin0",
    create: "Lütfen Ödül Adını Girin1",
    upload: "Lütfen Ödül Adını Girin2",
    selectMember: "Lütfen Ödül Adını Girin3",
    members: "Lütfen Ödül Adını Girin4",
    category: "Lütfen Ödül Adını Girin5",
    approvers: "Lütfen Ödül Adını Girin6",
    rewardTo: "Lütfen Ödül Adını Girin7",
    createReward: "Lütfen Ödül Adını Girin8",
    forApproval: "Lütfen Ödül Adını Girin9",
    deductionPerMonth: "Ödül Nedenini Girin0",
    pleaseEnterloanTenureInMonths: "Ödül Nedenini Girin1",
    amount: "Ödül Nedenini Girin2",
    pleaseEnterAmount: "Ödül Nedenini Girin3",
    purpose: "Ödül Nedenini Girin4",
    selectPurpose: "Ödül Nedenini Girin5",
    deadline: "Ödül Nedenini Girin6",
    description: "Ödül Nedenini Girin7",
    enterDescription: "Ödül Nedenini Girin8",
    loanPurpose: {
      vehicle: "Ödül Nedenini Girin9",
      personal: "Neden0",
      wedding: "Neden1",
      medical: "Neden2",
      education: "Neden3",
      house: "Neden4",
      other: "Neden5",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default turkish;
