const arabic = {
  resignationDictionary: {
    enterRewardName: "أدخل اسم المكافأة",
    pleaseEnterRewardName: "الرجاء إدخال اسم المكافأة",
    enterRewardReason: "أدخل سبب المكافأة",
    reason: "السبب",
    name: "الاسم",
    filter: "عامل التصفية",
    tableView: "عرض الجدول",
    listView: "عرض القائمة",
    complainOf: "شكوى من",
    selectApprovers: "تحديد الموافقين",
    reward: "الرجاء إدخال اسم المكافأة0",
    create: "الرجاء إدخال اسم المكافأة1",
    upload: "الرجاء إدخال اسم المكافأة2",
    selectMember: "الرجاء إدخال اسم المكافأة3",
    members: "الرجاء إدخال اسم المكافأة4",
    category: "الرجاء إدخال اسم المكافأة5",
    approvers: "الرجاء إدخال اسم المكافأة6",
    rewardTo: "الرجاء إدخال اسم المكافأة7",
    createReward: "الرجاء إدخال اسم المكافأة8",
    forApproval: "الرجاء إدخال اسم المكافأة9",
    deductionPerMonth: "أدخل سبب المكافأة0",
    pleaseEnterloanTenureInMonths: "أدخل سبب المكافأة1",
    amount: "أدخل سبب المكافأة2",
    pleaseEnterAmount: "أدخل سبب المكافأة3",
    purpose: "أدخل سبب المكافأة4",
    selectPurpose: "أدخل سبب المكافأة5",
    deadline: "أدخل سبب المكافأة6",
    description: "أدخل سبب المكافأة7",
    enterDescription: "أدخل سبب المكافأة8",
    loanPurpose: {
      vehicle: "أدخل سبب المكافأة9",
      personal: "السبب0",
      wedding: "السبب1",
      medical: "السبب2",
      education: "السبب3",
      house: "السبب4",
      other: "السبب5",
    },
  },

  /*** Define language write side ***/
  Direction: "rtl",
};
export default arabic;
