const urdu = {
  resignationDictionary: {
    resignation: "استعفیٰ",
    resignationDetail: "استعفیٰ کی تفصیل",
    enterRewardName: "انعام کا نام درج کریں",
    pleaseEnterRewardName: "برائے مہربانی انعام کا نام درج کریں۔",
    enterRewardReason: "انعام کی وجہ درج کریں",
    reason: "وجہ",
    name: "نام",
    filter: "فلٹر",
    tableView: "میز کا منظر",
    listView: "فہرست دیکھیں",
    complainOf: "کی شکایت",
    selectApprovers: "منظور کنندگان کو منتخب کریں۔",
    reward: "انعام",
    create: "بنانا",
    upload: "اپ لوڈ",
    selectMember: "ممبر کو منتخب کریں۔",
    members: "اراکین",
    category: "قسم",
    approvers: "منظوری دینے والے",
    rewardTo: "کو انعام",
    myComplain: "میری شکایت",
    complainToMe: "مجھ سے شکایت",
    createReward: "اجر پیدا کریں",
    forApproval: "منظوری کے لیے",
    deductionPerMonth: "مہینے/کٹوتی",
    pleaseEnterloanTenureInMonths: "براہ کرم قرض کی مدت درج کریں",
    amount: "رقم",
    pleaseEnterAmount: "براہ کرم رقم درج کریں",
    deadline: "ڈیڈ لائن",
    purpose: "مقصد",
    selectPurpose: "مقصد منتخب کریں",
    description: "تفصیل",
    enterDescription: "تفصیل درج کریں",
    createResignation: " استعفیٰ بنائیں",
    createdByMe: "میرے ذریعہ تخلیق کردہ",
    table: "ٹیبل",
    list: "فہرست",
    selectReason: "وجہ منتخب کریں",
    type: "قسم",
    selectType: "قسم منتخب کریں",
    selectMember: "ممبر منتخب کریں",
    search: "تلاش کریں",
    resignationDate: "استعفیٰ کی تاریخ",
    selectDate: "تاریخ منتخب کریں",
    manager: "مینیجر",
    selectManager: "مینیجر کو منتخب کریں",
    hr: "HR",
    selectHr: "HR منتخب کریں",
    finance: "مالیات",
    selectFinance: "فنانس کو منتخب کریں",
    IT: "یہ",
    selectItMember: "آئی ٹی ممبر کو منتخب کریں",

    admin: "ایڈمن",
    selectAdmin: "ایڈمن کو منتخب کریں",
    otherApprovals: "دیگر منظوریاں",
    exitInterview: "انٹرویو سے باہر نکلیں",
    referenceNo: "حوالہ نمبر",
    status: "حالت",
    date: "تاریخ",
    creator: "خالق",

    loanPurpose: {
      vehicle: "گاڑی",
      personal: "ذاتی",
      wedding: "شادی",
      medical: "طبی",
      education: "تعلیم",
      house: "گھر",
      other: "دوسرے",
    },
  },
  /*** Define language write side ***/
  Direction: "rtl",
};
export default urdu;
