const en = {
  loanDictionaryList: {
    loans: "Loans",
    filter: "Filter",
    selectApprovers: "Select Approvers",
    warning: "Warning",
    create: "Create",
    upload: "Upload",
    tableView: "Table View",
    listView: "List View",
    selectMember: "Select Members",
    members: "Members",
    category: "Category",
    approvers: "Approvers",
    warningTo: "Warning To",
    myWarning: "My Warning",
    warningToMe: "Warning To Me",
    createLoan: "Create Loan",
    forApproval: "For Approval",
    deductionPerMonth: "Deduction/Months",
    pleaseEnterloanTenureInMonths: "Please enter loan tenure",
    amount: "Amount",
    pleaseEnterAmount: "Please enter amount",
    purpose: "Purpose",
    selectPurpose: "Select purpose",
    deadline: "Deadline",
    description: "Description",
    enterDescription: "Enter Description",
    loanTenure: "Loan Tenure (In Months)",
    months: "months",
    datePicker: "Date Picker",
    loansToMe: "Loans To Me",
    listL: "List",
    table: "Table",
    loanPurpose: {
      LoanPurpose: "Loan Purpose",
      vehicle: "Vehicle",
      personal: "Personal",
      wedding: "Wedding",
      medical: "Medical",
      education: "Education",
      house: "House",
      other: "Other",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default en;
