const arabic = {
  ExpenseDictionaryList: {
    createTextBtn: "إنشاء حساب",

    labels: {
      category: "فئة",
      approvals: "الموافقات ",
      myExpense: "مصاريفي  ",
      forExecution: "للتنفيذ",
      forFinance: "للتمويل",
      approvers: "الموافقون",
      financers: "الممولين",
      executors: "المنفذين",
      executor: "المنفذ",
      finance: "المالية",
      inProcess: " تحت المعالجة ",
      testProject: "اختبار المشروع      ",
      transport: "المواصلات",
      header: "رأس",
      expenseDate: "تاريخ المصاريف      ",
      expenseDetail: "تفاصيل المصاريف      ",

      food: "غذاء",
      shopping: "التسوق",
      office: "مكتب",
      fuel: "الوقود",
      entertainment: "وسائل الترفيه      ",
      travel: "يسافر",
      health: "صحة",
      types: "أنواع",
      assets: "أصول      ",
      group: "مجموعة",
      project: "مشروع",
      general: "جنرال لواء",
      date: "تاريخ",
      amount: "مقدار",
      description: "وصف",
      attachments: "المرفقات",
      createExpense: "خلق المصاريف      ",
      isReimbursable: "قابل للسداد      ",
    },
    placeHolder: {
      writeHeaderHere: "اكتب العنوان هنا...",
      pickCurrentDate: "اختر التاريخ الحالي",
      enterAmount: "أدخل المبلغ",
      selectApprovers: "حدد الموافقون",
      selectFinancers: "حدد الممولين",
      selectExecutors: "حدد المنفذين",
      writeDescription: "اكتب الوصف هنا ...",
    },
  },
  Direction: "rtl",
};
export default arabic;
