const en = {
  ExpenseDictionaryList: {
    createTextBtn: "Create Expense",

    labels: {
      category: "Category",
      approvals: "Approvals",
      myExpense: "My Expense",
      forExecution: "For Excecution",
      forFinance: "For Finance",
      approvers: "Approvers",
      financers: "Financers",
      executors: "Executors",
      executor: "Executor",
      finance: "Finance",
      inProcess: "In Process",
      testProject: "Test Project",
      transport: "Transport",
      header: "Header",
      expenseDate: "Expense Date",
      expenseDetail: "Expense Detail",
      food: "Food",
      shopping: "Shopping",
      office: "Office",
      fuel: "Fuel",
      entertainment: "Entertainment",
      travel: "Travel",
      health: "Health",
      types: "Types",
      assets: "Assets",
      group: "Group",
      project: "Project",
      general: "General",
      date: "Date",
      amount: "Amount",
      description: "Description",
      attachments: "Attachments",
      createExpense: "Create Expense",
      isReimbursable: "Is Reimbursable",
    },
    placeHolder: {
      writeHeaderHere: "Write Header Here...",
      pickCurrentDate: "Select Date",
      enterAmount: "Enter Amount",
      selectApprovers: "Select Approvers",
      selectFinancers: "Select Financers",
      selectExecutors: "Select Executors",
      writeDescription: "Write Description Here ...",
    },
  },
  Direction: "ltr",
};
export default en;
