const hindi = {
  ExpenseDictionaryList: {
    createTextBtn: "व्यय बनाएँ",

    labels: {
      category: "श्रेणी",
      approvals: "स्वीकृति",
      myExpense: "मेरा खर्च",
      forExecution: "निष्पादन के लिए",
      forFinance: "वित्त के लिए",
      approvers: "अनुमोदक",
      financers: "फाइनेंसरों",
      executors: "निष्पादकों",
      executor: "निर्वाहक",
      finance: "वित्त",
      inProcess: "इस प्रक्रिया में",
      testProject: "परीक्षण परियोजना",
      transport: "यातायात",
      header: "हैडर",
      expenseDate: "व्यय तिथि",
      expenseDetail: "व्यय विवरण",
      food: "भोजन",
      shopping: "खरीदारी",
      office: "कार्यालय",
      fuel: "ईंधन",
      entertainment: "मनोरंजन",
      travel: "यात्रा करना",
      health: "स्वास्थ्य",
      types: "प्रकार",
      assets: "Assets",
      group: "समूह",
      project: "परियोजना",
      general: "सामान्य",
      date: "दिनांक",
      amount: "राशि",
      description: "विवरण",
      attachments: "संलग्नक",
      createExpense: "व्यय बनाएँ",
      isReimbursable: "प्रतिपूर्ति योग्य है",
    },
    placeHolder: {
      writeHeaderHere: "यहां हैडर लिखें...",
      pickCurrentDate: "वर्तमान तिथि चुनें",
      enterAmount: "राशि डालें",
      selectApprovers: "स्वीकृतकर्ताओं का चयन करें",
      selectFinancers: "फाइनेंसरों का चयन करें",
      selectExecutors: "निष्पादकों का चयन करें",
      writeDescription: "विवरण यहाँ लिखें...",
    },
  },
  Direction: "ltr",
};
export default hindi;
