const turkish = {
  ExpenseDictionaryList: {
    createTextBtn: "Gider Oluştur",
    labels: {
      category: "Kategori",
      approvals: "Onaylar",
      myExpense: "Giderim",
      forExecution: "Uygulama için",
      forFinance: "Finans için",
      approvers: "Onaylayanlar",
      financers: "Finansörler",
      executors: "Yürütücüler",
      executor: "Yürütücü",
      finance: "Kategori0",
      inProcess: "Kategori1",
      testProject: "Kategori2",
      transport: "Kategori3",
      header: "Kategori4",
      expenseDate: "Kategori5",
      expenseDetail: "Kategori6",
      food: "Kategori7",
      shopping: "Kategori8",
      office: "Kategori9",
      fuel: "Onaylar0",
      entertainment: "Onaylar1",
      travel: "Onaylar2",
      health: "Onaylar3",
      types: "Onaylar4",
      assets: "Onaylar5",
      group: "Onaylar6",
      project: "Onaylar7",
      general: "Onaylar8",
      date: "Onaylar9",
      amount: "Giderim0",
      description: "Giderim1",
      attachments: "Giderim2",
      createExpense: "Gider Oluştur",
      isReimbursable: "Giderim3",
    },
    placeHolder: {
      writeHeaderHere: "Giderim4",
      pickCurrentDate: "Giderim5",
      enterAmount: "Giderim6",
      selectApprovers: "Giderim7",
      selectFinancers: "Giderim8",
      selectExecutors: "Giderim9",
      writeDescription: "Uygulama için0",
    },
  },
  Direction: "ltr",
};
export default turkish;
