export const SearchFilterEnum = {
  All: 0,
  Feed: 1,
  Lead: 2,
  Travel: 3,
  Document: 4,
  Project: 5,
  WorkBoard: 6,
  Group: 7,
  Expense: 8,
  Task: 9,
  Employee: 10,
  ELearningCourse: 11,
  ELearningVideos: 12,
  ELearningArticles: 13,
  ELearningQuiz: 14,
  ELearningBook: 15,
  ELearningTedTalks: 16,
};
