const en = {
  leaveDictionary: {
    leave: "Leave",
    myLeaves: "My Leaves",
    days: "Days",
    endDate: "End Date",
    startDate: "Start Date",
    enterRewardName: "Entet Reward Name",
    pleaseEnterRewardName: "Please Enter Reward Name",
    enterRewardReason: "Enter Reward Reason",
    reason: "Reason",
    name: "Name",
    filter: "Filter",
    tableView: "Table View",
    listView: "List View",
    complainOf: "Complain Of",
    selectApprovers: "Select Approvers",
    reward: "Reward",
    create: "Create",
    upload: "Upload",
    selectMember: "Select Members",
    members: "Members",
    category: "Category",
    approvers: "Approvers",
    rewardTo: "Reward To",
    createleave: "Create Leave",
    forApproval: "For Approval",
    deductionPerMonth: "Deduction/Months",
    pleaseEnterloanTenureInMonths: "Please enter loan tenure",
    amount: "Amount",
    pleaseEnterAmount: "Please enter amount",
    purpose: "Purpose",
    selectPurpose: "Select purpose",
    deadline: "Deadline",
    description: "Description",
    enterDescription: "Enter Description",
    leaveType: "Leave Type",
    selectType: "Select Type",
    onBehalfOf: "On Behalf Of",
    leaveDates: "Leave Dates",
    startDate: "Start Date",
    endDate: "End Date",
    createdByMe: "Created By Me",
    forApproval: "For Approval",
    leaveToMe: "Leave to Me",
    table: "Table",
    list: "List",
    referenceNo: "Reference No",
    creator: "Creator",
    status: "Status",

    loanPurpose: {
      vehicle: "Vehicle",
      personal: "Personal",
      wedding: "Wedding",
      medical: "Medical",
      education: "Education",
      house: "House",
      other: "Other",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default en;
