const hindi = {
  leaveDictionary: {
    leave: "छोड़ें",
    myLeaves: "मेरी पत्तियां",
    days: "दिन",
    endDate: "समाप्ति तिथि",
    startDate: "प्रारंभ तिथि",
    enterRewardName: "एंटेट इनाम का नाम",
    pleaseEnterRewardName: "कृपया इनाम का नाम दर्ज करें",
    enterRewardReason: "इनाम कारण दर्ज करें",
    reason: "कारण",
    name: "नाम",
    filter: "मेरी पत्तियां0",
    tableView: "मेरी पत्तियां1",
    listView: "मेरी पत्तियां2",
    complainOf: "मेरी पत्तियां3",
    selectApprovers: "मेरी पत्तियां4",
    reward: "मेरी पत्तियां5",
    create: "मेरी पत्तियां6",
    upload: "मेरी पत्तियां7",
    selectMember: "मेरी पत्तियां8",
    members: "मेरी पत्तियां9",
    category: "दिन0",
    approvers: "दिन1",
    rewardTo: "दिन2",
    createleave: "दिन3",
    forApproval: "दिन4",
    deductionPerMonth: "दिन5",
    pleaseEnterloanTenureInMonths: "दिन6",
    amount: "दिन7",
    pleaseEnterAmount: "दिन8",
    purpose: "दिन9",
    selectPurpose: "समाप्ति तिथि0",
    deadline: "समाप्ति तिथि1",
    description: "समाप्ति तिथि2",
    enterDescription: "समाप्ति तिथि3",
    loanPurpose: {
      vehicle: "वाहन",
      personal: "व्यक्तिगत",
      wedding: "शादी",
      medical: "चिकित्सा",
      education: "शिक्षा",
      house: "घर",
      other: "अन्य",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default hindi;
