const turkish = {
  leaveDictionary: {
    leave: "İzin",
    myLeaves: "İzinlerim",
    days: "Günler",
    endDate: "Bitiş Tarihi",
    startDate: "Başlangıç ​​Tarihi",
    enterRewardName: "Entet Ödül Adı",
    pleaseEnterRewardName: "Lütfen Ödül Adını Girin",
    enterRewardReason: "Ödül Nedenini Girin",
    reason: "Nedeni",
    name: "Ad",
    filter: "İzinlerim0",
    tableView: "İzinlerim1",
    listView: "İzinlerim2",
    complainOf: "İzinlerim3",
    selectApprovers: "İzinlerim4",
    reward: "İzinlerim5",
    create: "İzinlerim6",
    upload: "İzinlerim7",
    selectMember: "İzinlerim8",
    members: "İzinlerim9",
    category: "Günler0",
    approvers: "Günler1",
    rewardTo: "Günler2",
    createleave: "Günler3",
    forApproval: "Günler4",
    deductionPerMonth: "Günler5",
    pleaseEnterloanTenureInMonths: "Günler6",
    amount: "Günler7",
    pleaseEnterAmount: "Günler8",
    purpose: "Günler9",
    selectPurpose: "Bitiş Tarihi0",
    deadline: "Bitiş Tarihi1",
    description: "Bitiş Tarihi2",
    enterDescription: "Bitiş Tarihi3",
    loanPurpose: {
      vehicle: "Bitiş Tarihi4",
      personal: "Bitiş Tarihi5",
      wedding: "Bitiş Tarihi6",
      medical: "Bitiş Tarihi7",
      education: "Bitiş Tarihi8",
      house: "Bitiş Tarihi9",
      other: "Başlangıç ​​Tarihi0",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default turkish;
