const urdu = {
  leaveDictionary: {
    leave: "چھوڑ دو",
    myLeaves: "میری چھٹی",
    days: "دن",
    endDate: "آخری تاریخ",
    startDate: "شروع کرنے کی تاریخ",
    enterRewardName: "انعام کا نام درج کریں",
    pleaseEnterRewardName: "برائے مہربانی انعام کا نام درج کریں۔",
    enterRewardReason: "انعام کی وجہ درج کریں",
    reason: "وجہ",
    name: "نام",
    filter: "فلٹر",
    tableView: "میز کا منظر",
    listView: "فہرست دیکھیں",
    complainOf: "کی شکایت",
    selectApprovers: "منظور کنندگان کو منتخب کریں۔",
    reward: "انعام",
    create: "بنانا",
    upload: "اپ لوڈ",
    selectMember: "ممبر کو منتخب کریں۔",
    members: "اراکین",
    category: "قسم",
    approvers: "منظوری دینے والے",
    rewardTo: "کو انعام",
    myComplain: "میری شکایت",
    complainToMe: "مجھ سے شکایت",
    createleave: "چھٹی بنائیں",
    forApproval: "منظوری کے لیے",
    deductionPerMonth: "مہینے/کٹوتی",
    pleaseEnterloanTenureInMonths: "براہ کرم قرض کی مدت درج کریں",
    amount: "رقم",
    pleaseEnterAmount: "براہ کرم رقم درج کریں",
    deadline: "ڈیڈ لائن",
    purpose: "مقصد",
    selectPurpose: "مقصد منتخب کریں",
    description: "تفصیل",
    enterDescription: "تفصیل درج کریں",
    leaveType: "چھوڑنے کی قسم",
    selectType: "قسم منتخب کریں",
    onBehalfOf: "کی جانب سے",
    leaveDates: "تاریخیں چھوڑیں",
    startDate: "شروع کرنے کی تاریخ",
    endDate: "آخری تاریخ",
    createdByMe: "میرے ذریعہ تخلیق کردہ",
    forApproval: "منظوری کے لیے",
    leaveToMe: "مجھ پر چھوڑ دو",
    table: "ٹیبل",
    list: "فہرست",
    referenceNo: "حوالہ نمبر",
    creator: "خالق",
    status: "حالت",
    loanPurpose: {
      vehicle: "گاڑی",
      personal: "ذاتی",
      wedding: "شادی",
      medical: "طبی",
      education: "تعلیم",
      house: "گھر",
      other: "دوسرے",
    },
  },
  /*** Define language write side ***/
  Direction: "rtl",
};
export default urdu;
