const en={
    salary_Dictionary:{
        Salary:"Salary",
        CreateSalary:"Create Salary",
        Search:"Search",
        Salaries:"Salaries",
        CreatedByMe:"Created By Me",
        ForApproval:"For Approval",
        List:"List",
        Approved:"Approved",
        NoDescription:"No Description",
        SalaryFor:"Salary For",
        EffectiveDate:"Effective Date",
        BasicSalary:"Basic Salary",
        NetSalary:"Net Salary",
        Approvers:"Approvers",
        Table:"Table",
        Reference:"Reference",
        ReferenceNo:"ReferenceNo",
        Creator:"Creator",
        Status:"Status",
        AllowanceDetail:"Allowance Detail",
        Allowance:"Allowance",
        Type:"Type",
        Amount:"Amount",
        SNo:"S No",
        Employee:"Employee",
        Grade:"Grade",
        Allowances:"Allowances",
        Deductions:"Deductions",
        Descrption:"Description",
        TotalAmount:"Total Amount",
        Approvals:"Approvals",
        user:"user",
        SalaryHeaders:"SalaryHeaders",
        Check:"check",
        GrossSalary:"GrossSalary",
        SalaryHeaders:"Salary Headers",
        SelectSalaryHeaders:"Select Salary Headers",
        SelectDate:"Select Date",
        EnterDescription:"Enter Description",
        Clear:"clear",
        SalaryInfo:"Salary Info",
        AddSalary:"Add Salary",
    }
}
export default en;