const urdu = {
  salaryDictionary: {
    salary: "تنخواہ",
    createSalary: "تنخواہ بنائیں",
    salaries: "تنخواہیں",
    createdByMe: "میرے ذریعہ تخلیق کردہ",
    forApproval: "منظوری کے لیے",
    list: "فہرست",
    table: "ٹیبل",
    salaryFor: "کے لیے تنخواہ",
    EffectiveDate: "مؤثر تاریخ",
    BasicSalary: "بنیادی تنخواہ",
    NetSalary: "خالص تنخواہ",
    Approvers: "منظور کرنے والے",
    Approvals: "منظوری",
    referenceno: "حوالہ نمبر",
    creator: "خالق",
    status: "حالت",
    employee: "ملازم",
    grade: "گریڈ",
    allowaces: "الاؤنسز",
    deductions: "کٹوتیاں",
    description: "تفصیل",
    sno: "سیریل نمبر.",
    totalAmount: "کل رقم",
  },
  Direction: "rtl",
};
export default urdu;
