const en = {
  LeadManagerDictionaryList: {
    firstLeadManager: "First Lead Manager",
    createTextBtn: "Create Lead Category Group",
    email: "Email",
    dashboard: "Dashboard",
    topBar: {
      search: "Search",
      filter: "Filter",
      list: "List",
      table: "Table",
      email: "Email",
      board: "Board",
    },
    placeHolder: {
      grpNamePH: "Enter group name",
      grpNameDescPH: "Enter group description",
      serachMembersPH: "Search members",
      writeName: "Write Name...",
      leadPhoneNumber: "Lead Phone Number",
      leadEmailAddress: "Lead Email Address",
      leadAddress: "Lead Address",
      leadUrl: "Lead Url",
      leadWebiste: "Lead Website",
      leadName: "Lead Name",
      selectFriendlyStatus: "Select Friendly Status",
      writeName: "Write name",
      writePhoneNumber: "Write phone number",
      writeEmailAddress: "Write email address",
      writeOfficeAddress: "Write office address",
      writeAddress: "Write address",
      selectGender: "Select gender",
      writeDesignation: "Write designation",
      writeDescription: "Write description",
      selectActiveStatus: "Select Active Status",
      to: "To:",
      subject: "Subject",
    },
    labels: {
      update: "Update",
      createGrp: "Create Group",
      updateGrp: "Update Group",
      upload: "Upload",
      add: "Add",
      cancel: "Cancel",
      send: "Send",
      preview: "Preview",
      grpName: "Group Name",
      grpDescription: "Group Description",
      members: "Members",
      public: "Public",
      private: "Private",
      uploadCvr: "Upload Cover",
      uplpadImage: "Upload Image",
      friendlyStatus: "Friendly Status",
      name: "Name",
      phone: "Phone",
      email: "Email",
      officeAddress: "Office Address",
      address: "Address",
      gender: "Gender",
      male: "Male",
      female: "Female",
      designation: "Designation",
      description: "Description",
      addContact: "Add Contact",
      updateContact: "Update Contact",
      mr: "Mr",
      ms: "Ms",
      mrs: "Mrs",
      activeStatus: "Active Status",
      section: "Section",
      composeEmail: "Compose Email",
    },
    detail: {
      details: "Details",
      assignMembers: "Assign Members",
      business: "Business",
      individual: "Individual",
      name: "Name",
      phoneNumber: "Phone Number",
      email: "Email",
      address: "Address",
      website: "Website",
      meetings: "Meetings",
      noMeetings: "No Meetings",
      contacts: "Contacts",
      noContacts: "No Contacts",
      contactDetail: "Contact Detail",
    },
    table: {
      name: "Name",
      description: "Description",
      members: "Members",
      createDate: "Created Date",
      address: "Address",
      type: "Type",
      section: "Section",
    },
    status: {
      friendly: "Friendly",
      neutral: "Neutral",
      unfriendly: "Unfriendly",
      active: "Active",
      inActive: "In-Active",
    },
  },
  Direction: "ltr",
};
export default en;
