const urdu = {
  LeadManagerDictionaryList: {
    createTextBtn: "لیڈ کیٹیگری گروپ بنائیں",
    firstLeadManager: "فرسٹ لیڈ مینیجر",

    email: "ای میل",
    dashboard: "ڈیش بورڈ",
    topBar: {
      search: "تلاش کریں",
      filter: "فلٹر",
      list: "فہرست",
      table: "ٹیبل",
      email: "ای میل",
      board: "بورڈ",
    },
    placeHolder: {
      grpNamePH: "گروپ کا نام درج کریں",
      grpNameDescPH: "گروپ کی تفصیل درج کریں",
      serachMembersPH: "میمبرز تلاش کریں",
      writeName: "نام لکھیں",
      leadPhoneNumber: "لیڈ فون نمبر",
      leadEmailAddress: "لیڈ ای میل ایڈریس",
      leadAddress: "لیڈ ایڈریس",
      leadUrl: "لیڈ یو آر ایل",
      leadWebiste: "لیڈ ویب سائٹ",
      leadName: "لیڈ کا نام",
      selectFriendlyStatus: "دوستانہ حیثیت کو منتخب کریں",
      writeName: "نام لکھیں",
      writePhoneNumber: "فون نمبر لکھیں",
      writeEmailAddress: "ای میل ایڈریس لکھیں",
      writeOfficeAddress: "دفتر کا پتہ لکھیں",
      writeAddress: "پتہ لکھیں",
      selectGender: "جنس منتخب کریں",
      writeDesignation: "عہدہ لکھیں",
      writeDescription: "تفصیل لکھیں",
      selectActiveStatus: "فعال حیثیت کو منتخب کریں",
      to: "کو",
      subject: "مضمون",
    },
    labels: {
      update: "اپ ڈیٹ",
      createGrp: "گروپ بنائیں",
      updateGrp: "اپ ڈیٹ گروپ",
      upload: "اپ لوڈ کریں",
      add: "شامل کریں",
      cancel: "منسوخ کریں",
      send: "بھیجیں",
      preview: "پیش نظارہ",
      grpName: "گروپ کا نام",
      grpDescription: "گروپ کی تفصیل",
      members: "ممبران",
      public: "عوام",
      private: "نجی",
      uploadCvr: "کور اپ لوڈ کریں",
      uplpadImage: "تصویر اپ لوڈ کریں",
      friendlyStatus: "دوستانہ حیثیت",
      name: "نام",
      phone: "فون",
      email: "ای میل",
      officeAddress: "دفتر کا پتہ",
      address: "پتہ",
      gender: "صنف",
      male: "مرد",
      female: "عورت",
      designation: "عہدہ",
      description: "تفصیل",
      addContact: "رابطہ شامل کریں",
      updateContact: "رابطہ کو اپ ڈیٹ کریں",
      mr: "مسٹر",
      ms: "مس",
      mrs: "مسز",
      activeStatus: "فعال حیثیت",
      section: "سیکشن",
      composeEmail: "ای میل لکھیں",
    },
    detail: {
      details: "تفصیلات",
      assignMembers: "اراکین کو تفویض کریں",
      business: "کاروبار",
      individual: "انفرادی",
      name: "نام",
      phoneNumber: "فون نمبر",
      email: "ای میل",
      address: "پتہ",
      website: "ویب سائٹ",
      meetings: "ملاقاتیں",
      noMeetings: "کوئی ملاقاتیں نہیں",
      contacts: "رابطے",
      noContacts: "کوئی رابطے نہیں",
      contactDetail: "رابطہ کی تفصیل",
    },
    table: {
      name: "نام",
      description: "تفصیل",
      members: "ممبران",
      createDate: "تشکیل کی تاریخ",
      address: "پتہ",
      type: "قسم",
      members: "اراکین",
      section: "سیکشن",
    },
    status: {
      friendly: "دوستانہ",
      neutral: "غیر جانبدار",
      unfriendly: "غیر دوستانہ",
      active: "فعال",
      inActive: "غیر فعال",
    },
  },
  Direction: "rtl",
};
export default urdu;
