const hindi = {
  CareerDictionaryList: {
    createTextBtn: "Create Career",

    labels: {
      firstName: "First Name",
      enterFirstName: "Enter First Name",
      lastName: "Last Name",
      enterLastName: "Enter Last Name",
      email: "Email",
      enterEmail: "Enter Email",
      phoneNumber: "Phone Number",
      enterPhoneNumber: "Enter Phone Number",
      currentSalary: "Current Salary",
      expectedSalary: "Expected Salary",
      experience: "Experience",
      noticePeriod: "Notice Period",
      coverNote: "Cover Note",
      attachment: "Attachment",
      upload: "upload",
      applyJob: "Apply Job",
      enter: "Enter",
      category: "Category",
      approvals: "Approvals",
      myCareer: "My Career",
      careers: "Career",
      forApproval: "For Approval",
      approvers: "Approvers",
      inProcess: "In Process",
      testProject: "Test Project",
      header: "Header",
      list: "List",
      table: "Table",
      applyNow: "Apply Now",
      copyLink: "Copy Link",
      salaryRange: "Salary Range",
      effectiveDate: "Effective Date",
      experienceRequired: "Experience Required",
      jobExpires: "Job Expires",
      designation: "Designation",
      jobdescription: "Job Description",
      designation: "Designation",
      jobdescription: "Job Description",
      department: "Department",
      supervisor: "Supervisor",
      interviewers: "Interviewers",
      postInterviewers: "Post Interviewers",
      hiringBuddy: "Hiring Buddy",
      jobviewer: "Job viewers",
      city: "City",
      skills: "Skills",
      experienceLabel: "Experience (Years)",
      jobType: "Job Type",
      jobShift: "Job Shift",
      education: "Education",
      careerLevel: "Career Level",
      endDate: "End Date",
      reviewCriteria: "Review Criteria",
      skillsRequired: "Skills Reuired",
      createJob: "Create Job",
      expenseDate: "Expense Date",
      expenseDetail: "Expense Detail",
      food: "Food",
      shopping: "Shopping",
      office: "Office",
      fuel: "Fuel",
      entertainment: "Entertainment",
      travel: "Travel",
      health: "Health",
      types: "Types",
      assets: "Assets",
      group: "Group",
      project: "Project",
      general: "General",
      date: "Date",
      appliedDate: "Applied Date",
      amount: "Amount",
      description: "Description",
      attachments: "Attachments",
      createExpense: "Create Expense",
      isReimbursable: "Is Reimbursable",
      jobdetails: "Job Details",
      jobTitle: "Job Title",
      createdBy: "Created By",
      educationLevel: "Education Level",
      yearOfExperience: "Year Of Experience",
      applicants: "Applicants",
      shortListed: "Short Listed",
      rejected: "Rejected",
      completed: "Completed",
      finalist: "Finalist",
      maybe: "Maybe",
      careerdetail: "Career Detail",
    },
    placeHolder: {
      writeHeaderHere: "Write Header Here...",
      pickCurrentDate: "Pick Current Date",
      enterAmount: "Enter Amount",
      selectApprovers: "Select Approvers",
      selectFinancers: "Select Financers",
      selectExecutors: "Select Executors",
      selectDesignation: "Select Designation",
      writeDescription: "Write Description Here ...",
      enterMinSalary: "Enter Minimum Salary",
      enterMaxSalary: "Enter Maximun Salary",
      selectDepartment: "Select Department",
      selectSupervisor: "Select Supervisor",
      selectInterviewers: "Select Interviewer",
      selectPostInterviewers: "Select Post Interviewers",
      selectApprovers: "Select Approvers",
      selectCity: "Select City",
      addSkills: "Add Skill",
      selectJobType: "Select Job Type",
      selectJobshift: "Select Job Shift",
      selectEducation: "Please Select Eduction",
      selectCareerLevel: "Select Career Level",
      selectEndDate: "Select End Date",
      reviewcriteria: "Enter Review Criteria",
    },
  },
  Direction: "ltr",
};
export default hindi;
