const hindi = {
  CareerDictionaryList: {
    createTextBtn: "Create Career",

    labels: {
      category: "Category",
      approvals: "Approvals",
      myCareer: "My Career",
      careers: "Career",
      forApproval: "For Approval",
      approvers: "Approvers",
      inProcess: "In Process",
      testProject: "Test Project",
      header: "Header",
      list: "List",
      table: "Table",
      apply: "Apply",
      copyLink: "Copy Link",
      expenseDate: "Expense Date",
      expenseDetail: "Expense Detail",
      food: "Food",
      shopping: "Shopping",
      office: "Office",
      fuel: "Fuel",
      entertainment: "Entertainment",
      travel: "Travel",
      health: "Health",
      types: "Types",
      assets: "Assets",
      group: "Group",
      project: "Project",
      general: "General",
      date: "Date",
      amount: "Amount",
      description: "Description",
      attachments: "Attachments",
      createExpense: "Create Expense",
      isReimbursable: "Is Reimbursable",
    },
    placeHolder: {
      writeHeaderHere: "Write Header Here...",
      pickCurrentDate: "Pick Current Date",
      enterAmount: "Enter Amount",
      selectApprovers: "Select Approvers",
      selectFinancers: "Select Financers",
      selectExecutors: "Select Executors",
      writeDescription: "Write Description Here ...",
    },
  },
  Direction: "ltr",
};
export default hindi;
