const urdu = {
  CareerDictionaryList: {
    createTextBtn: "اخراجات بنائیں",

    labels: {
      category: "قسم",
      approvals: "منظوری ",
      myCareer: "میرا پیشہ",
      careers: "کیریئر",
      forApproval: "منظوری کے لیے",
      forExecution: "عملدرآمد کے لیے",
      forFinance: "فنانس کے لیے",
      approvers: "منظور کرنے والے",
      financers: "فنانسرز",
      executors: "ایگزیکیوٹرز",
      executor: "عمل کرنے والا",
      finance: "مالیات",
      list: "فہرست",
      table: "ٹیبل",
      apply: "درخواست دیں",
      copyLink: "لنک کاپی کریں",
      salaryRange: "تنخواہ کی حد",
      effectiveDate: "مؤثر تاریخ",
      experienceRequired: "تجربہ درکار ہے",
      jobExpires: "ملازمت ختم ہو جاتی ہے",
      inProcess: " عمل میں",
      testProject: "ٹیسٹ پروجیکٹ",
      transport: "ٹرانسپورٹ",
      header: "ہیڈر",
      expenseDate: "اخراجات کی تاریخ:",
      expenseDetail: "اخراجات کی تفصیل",
      food: "کھانا",
      shopping: "خریداری",
      office: "دفتر",
      fuel: "ایندھن",
      entertainment: "تفریح",
      travel: "سفر",
      health: "صحت",
      types: "اقسام",
      assets: "اثاثے",
      group: "گروپ",
      project: "مشروع",
      general: "جنرال لواء",
      date: "تاريخ",
      amount: "مقدار",
      description: "وصف      ",
      attachments: "المرفقات",
      createExpense: "إنشاء حساب",
      isReimbursable: "قابل للسداد",
    },
    placeHolder: {
      writeHeaderHere: "یہاں ہیڈر لکھیں...",
      pickCurrentDate: "موجودہ تاریخ کا انتخاب کریں",
      enterAmount: "رقم درج کریں",
      selectApprovers: "منظور کنندگان کو منتخب کریں",
      selectFinancers: "فنانسرز کو منتخب کریں",
      selectExecutors: "ایگزیکٹوز کو منتخب کریں",
      writeDescription: "تفصیل یہاں لکھیں ...",
    },
  },
  Direction: "rtl",
};
export default urdu;
