const urdu = {
  CareerDictionaryList: {
    createTextBtn: "اخراجات بنائیں",
    Careers: "کیریئرز",
    labels: {
      firstName: "پہلا نام",
      enterFirstName: "پہلا نام درج کریں",
      lastName: "آخری نام",
      enterLastName: "آخری نام درج کریں",
      email: "ای میل",
      enterEmail: "ای میل درج کریں",
      phoneNumber: "فون نمبر",
      enterPhoneNumber: "فون نمبر درج کریں",
      currentSalary: "موجودہ تنخواہ",
      expectedSalary: "متوقع تنخواہ",
      experience: "تجربہ",
      coverNote: "کور نوٹ",
      noticePeriod: "نوٹس کی مدت",
      attachment: "منسلکہ",
      upload: "اپ لوڈ کریں",
      applyJob: "نوکری کا اطلاق کریں",
      category: "قسم",
      approvals: "منظوری ",
      myCareer: "میرا پیشہ",
      careers: "کیریئر",
      forApproval: "منظوری کے لیے",
      forExecution: "عملدرآمد کے لیے",
      forFinance: "فنانس کے لیے",
      approvers: "منظور کرنے والے",
      financers: "فنانسرز",
      executors: "ایگزیکیوٹرز",
      executor: "عمل کرنے والا",
      finance: "مالیات",
      list: "فہرست",
      table: "ٹیبل",
      applyNow: "درخواست دیں",
      copyLink: "لنک کاپی کریں",
      salaryRange: "تنخواہ کی حد",
      effectiveDate: "مؤثر تاریخ",
      experienceRequired: "تجربہ درکار ہے",
      jobExpires: "ملازمت ختم ہو جاتی ہے",
      designation: "عہدہ",
      jobdescription: "کام کی تفصیل",
      jobdescription: "کام کی تفصیل",
      department: "شعبہ",
      supervisor: "سپروائزر",
      interviewers: "انٹرویو لینے والے",
      postInterviewers: "انٹرویو لینے والوں کو پوسٹ کریں۔",
      hiringBuddy: "دوست کی خدمات حاصل کرنا",
      jobviewer: "ملازمت کے ناظرین",
      city: "شہر",
      skills: "ہنر",
      experienceLabel: "تجربہ (سال)",
      jobType: "ملازمت کی قسم",
      jobShift: "جاب شفٹ",
      education: "تعلیم",
      careerLevel: "کیریئر کی سطح",
      endDate: "آخری تاریخ",
      reviewCriteria: "جائزہ کے معیار",
      skillsRequired: "مہارت کی ضرورت ہے",
      createJob: "ملازمت پیدا کریں",
      inProcess: " عمل میں",
      testProject: "ٹیسٹ پروجیکٹ",
      transport: "ٹرانسپورٹ",
      header: "ہیڈر",
      expenseDate: "اخراجات کی تاریخ:",
      expenseDetail: "اخراجات کی تفصیل",
      food: "کھانا",
      shopping: "خریداری",
      office: "دفتر",
      fuel: "ایندھن",
      entertainment: "تفریح",
      travel: "سفر",
      health: "صحت",
      types: "اقسام",
      assets: "اثاثے",
      group: "گروپ",
      project: "مشروع",
      general: "جنرال لواء",
      date: "تاريخ",
      appliedDate: "درخواست کی تاریخ",
      amount: "مقدار",
      description: "وصف      ",
      attachments: "المرفقات",
      createExpense: "إنشاء حساب",
      isReimbursable: "قابل للسداد",
      jobdetails: "ملازمت کی تفصیلات",
      jobTitle: "ملازمت کا عنوان",
      createdBy: "بنائی گئی",
      educationLevel: "تعلیمی معیار",
      yearOfExperience: "تجربے کا سال",
      applicants: "درخواست دہندگان",
      shortListed: "مختصر فہرست",
      rejected: "مسترد",
      completed: "مکمل",
      finalist: "فائنلسٹ",
      maybe: "شاید",
      careerdetail: "کیریئر کی تفصیل",
      creator: "خالق",
      minSalary: "کم سے کم تنخواہ",
      maxSalary: "زیادہ سے زیادہ تنخواہ",
      manager: "مینیجر",
      members: "ممبران",
      interviewers: "انٹرویو لینے والے",
      postInterviewers: "انٹرویو لینے والوں کو پوسٹ کریں",
    },
    placeHolder: {
      writeHeaderHere: "یہاں ہیڈر لکھیں...",
      pickCurrentDate: "موجودہ تاریخ کا انتخاب کریں",
      enterAmount: "رقم درج کریں",
      selectApprovers: "منظور کنندگان کو منتخب کریں",
      selectFinancers: "فنانسرز کو منتخب کریں",
      selectExecutors: "ایگزیکٹوز کو منتخب کریں",
      selectDesignation: "عہدہ منتخب کریں",
      writeDescription: "تفصیل یہاں لکھیں ...",
      enterMinSalary: "کم از کم تنخواہ درج کریں۔",
      enterMaxSalary: "زیادہ سے زیادہ تنخواہ درج کریں۔",
      selectDepartment: "محکمہ منتخب کریں۔",
      selectSupervisor: "سپروائزر کو منتخب کریں۔",
      selectInterviewers: "انٹرویو لینے والے کو منتخب کریں۔",
      selectPostInterviewers: "پوسٹ انٹرویو لینے والوں کو منتخب کریں۔",
      selectCity: "شہر منتخب کریں۔",
      addSkills: "مہارت شامل کریں۔",
      selectJobType: "ملازمت کی قسم منتخب کریں۔",
      selectJobshift: "جاب شفٹ کو منتخب کریں۔",
      selectEduction: "برائے مہربانی تعلیم کو منتخب کریں۔",
      selectCareerLevel: "کیریئر کی سطح کو منتخب کریں۔",
      selectEndDate: "اختتامی تاریخ منتخب کریں۔",
      reviewcriteria: "جائزہ کا معیار درج کریں۔",
    },
  },
  Direction: "rtl",
};
export default urdu;
