const en = {
  documentDictionary: {
    DocsArchive: "Docs & Archive",
    AllDocuments: "All Documents",
    MyDocuments: "My Documents",
    ForApprovals: "For Approvals",
    Home: "Home",
    CreateDocument: "Create Document",
    NewFolder: "New Folder",
    UploadDocuments: "Upload Documents",
    AddMileBoard: "Add Mileboard",
    AddMilePad: "Add Milepad",
    AddMileGrid: "Add Milegrid",
    AddMileShow: "Add Mileshow",
    Download: "Download",
    CreateFolder: "Create Folder",
    Name: "Name",
    Description: "Description",
    Public: "Public",
    Private: "Private",
    Approvers: "Approvers",
    Collabrators: "Collabrators",
    Upload: "Upload",
    list: "List",
    table: "Table",
    enterName: "Enter Name",
    enterDescription: "Enter Description",
    readers: "Readers",
    selectReaders: "Select Readers",
    createMilepad: "Create Milepad",
    fileName: "File Name",
    shortDescription: "Short Description",
    selectApprovals: "Select Approvals",
    create: "Create",
    createMileboard: "Create Mileboard",
    createMilegrid: "Create Milegrid",
    createMileshow: "Create Mileshow",
    members: "Members",
    detail: "Detail",
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default en;
