const urdu = {
  documentDictionary: {
    DocsArchive: "دستاویزات اور آرکائیو",
    AllDocuments: "تمام دستاویزات",
    MyDocuments: "میرے دستاویزات",
    ForApprovals: "منظوریوں کے لیے",
    Home: "ہوم",
    CreateDocument: "دستاویز بنائیں",
    NewFolder: "نیا فولڈر",
    UploadDocuments: "دستاویزات اپ لوڈ کریں",
    AddMileBoard: "مائل بورڈ شامل کریں",
    AddMilePad: "مائل پیڈ شامل کریں",
    AddMileGrid: "شامل کریں",
    AddMileShow: "میل شو شامل کریں",
    Download: "ڈاؤن لوڈ کریں",
    CreateFolder: "فولڈر بنائیں",
    Name: "نام",
    Description: "تفصیل",
    Public: "عوامی",
    Private: "نجی",
    Approvers: "منظور کنندگان",
    Collabrators: "معاونین",
    Upload: "پ لوڈ کریں",
    list: "فہرست",
    table: "ٹیبل",
    enterName: "نام درج کریں",
    enterDescription: "تفصیل درج کریں",
    readers: "قارئین",
    selectReaders: "قارئین کو منتخب کریں",
    createMilepad: "میل پیڈ بنائیں",
    fileName: "فائل کا نام",
    shortDescription: "مختصر کوائف",
    selectApprovals: "منظوریوں کو منتخب کریں",
    create: "بنانا",
    createMileboard: "مائل بورڈ بنائیں",
    createMilegrid: "Milegrid بنائیں",
    createMileshow: "میل شو بنائیں",
    members: "ممبران",
    detail: "تفصیل",
  },
  /*** Define language write side ***/
  Direction: "rtl",
};
export default urdu;
