const urdu = {
  departmentDictionary: {
    departments: "شعبه جات",
    enterRewardName: "انعام کا نام درج کریں",
    pleaseEnterRewardName: "برائے مہربانی انعام کا نام درج کریں۔",
    enterRewardReason: "انعام کی وجہ درج کریں",
    reason: "وجہ",
    name: "نام",
    filter: "فلٹر",
    tableView: "میز کا منظر",
    listView: "فہرست دیکھیں",
    complainOf: "کی شکایت",
    selectApprovers: "منظور کنندگان کو منتخب کریں۔",
    reward: "انعام",
    create: "بنانا",
    upload: "اپ لوڈ",
    selectMember: "ممبر کو منتخب کریں۔",
    members: "اراکین",
    category: "قسم",
    approvers: "منظوری دینے والے",
    rewardTo: "کو انعام",
    myComplain: "میری شکایت",
    complainToMe: "مجھ سے شکایت",
    createDepartment: "محکمہ بنائیں",
    forApproval: "منظوری کے لیے",
    deductionPerMonth: "مہینے/کٹوتی",
    pleaseEnterloanTenureInMonths: "براہ کرم قرض کی مدت درج کریں",
    amount: "رقم",
    pleaseEnterAmount: "براہ کرم رقم درج کریں",
    deadline: "ڈیڈ لائن",
    purpose: "مقصد",
    selectPurpose: "مقصد منتخب کریں",
    description: "تفصیل",
    enterDescription: "تفصیل درج کریں",
    list: "فہرست",
    table: "ٹیبل",
    enterName: "نام درج کریں",
    uploads: "اپ لوڈز",
    headOfDepartment: "محکمہ کے سربراہ",
    selectHod: "HOD منتخب کریں",
    addEmployees: "ملازمین کو شامل کریں",
    deptName: "محکمہ کا نام",
    status: "حالت",
    createDate: "تاریخ بناؤ",
    addSubDepartment: "ذیلی محکمہ شامل کریں",
    appraisalQuestion: "تشخیص کا سوال",
    question: "سوال",
    enterQuestion: "سوال درج کریں",
    saveAppraisalQuestion: "تشخیصی سوال کو محفوظ کریں",
    addAppraisalQuestion: "تشخیصی سوال شامل کریں",
    clear: "صاف",

    loanPurpose: {
      vehicle: "گاڑی",
      personal: "ذاتی",
      wedding: "شادی",
      medical: "طبی",
      education: "تعلیم",
      house: "گھر",
      other: "دوسرے",
    },
  },
  /*** Define language write side ***/
  Direction: "rtl",
};
export default urdu;
