const en = {
  customApprovalDictionary: {
    customApproval: "Custom Approval",
    enterRewardName: "Entet Reward Name",
    pleaseEnterRewardName: "Please Enter Reward Name",
    enterRewardReason: "Enter Reward Reason",
    reason: "Reason",
    name: "Name",
    filter: "Filter",
    tableView: "Table View",
    listView: "List View",
    complainOf: "Complain Of",
    selectApprovers: "Select Approvers",
    reward: "Reward",
    create: "Create",
    upload: "Upload",
    selectMember: "Select Members",
    members: "Members",
    category: "Category",
    approvers: "Approvers",
    rewardTo: "Reward To",
    createCustomApproval: "Create Custom Approval",
    forApproval: "For Approval",
    approvalForMe: "Approval For Me",
    deductionPerMonth: "Deduction/Months",
    pleaseEnterloanTenureInMonths: "Please enter loan tenure",
    amount: "Amount",
    pleaseEnterAmount: "Please enter amount",
    purpose: "Purpose",
    selectPurpose: "Select purpose",
    deadline: "Deadline",
    description: "Description",
    enterDescription: "Enter Description",
    subject: "Subject",
    pleaseEnterSubject: "Please Enter Subject",
    customApprovals: "Custom Approvals",
    createdByMe: "Created By Me",
    list: "List",
    table: "Table",
    referenceNo: "Reference No",
    creator: "Creator",
    status: "Status",
    date: "Date",

    loanPurpose: {
      vehicle: "Vehicle",
      personal: "Personal",
      wedding: "Wedding",
      medical: "Medical",
      education: "Education",
      house: "House",
      other: "Other",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default en;
