const urdu = {
  customApprovalDictionary: {
    customApproval: "حسب ضرورت منظوری",

    enterRewardName: "انعام کا نام درج کریں",
    pleaseEnterRewardName: "برائے مہربانی انعام کا نام درج کریں۔",
    enterRewardReason: "انعام کی وجہ درج کریں",
    reason: "وجہ",
    name: "نام",
    filter: "فلٹر",
    tableView: "میز کا منظر",
    listView: "فہرست دیکھیں",
    complainOf: "کی شکایت",
    selectApprovers: "منظور کنندگان کو منتخب کریں۔",
    reward: "انعام",
    create: "بنانا",
    upload: "اپ لوڈ",
    selectMember: "ممبر کو منتخب کریں۔",
    members: "اراکین",
    category: "قسم",
    approvers: "منظوری دینے والے",
    rewardTo: "کو انعام",
    createCustomApproval: "حسب ضرورت منظوری بنائیں",
    myComplain: "میری شکایت",
    complainToMe: "مجھ سے شکایت",
    createReward: "اجر پیدا کریں",
    forApproval: "منظوری کے لیے",
    approvalForMe: "میرے لیے منظوری",
    deductionPerMonth: "مہینے/کٹوتی",
    pleaseEnterloanTenureInMonths: "براہ کرم قرض کی مدت درج کریں",
    amount: "رقم",
    pleaseEnterAmount: "براہ کرم رقم درج کریں",
    deadline: "ڈیڈ لائن",
    purpose: "مقصد",
    selectPurpose: "مقصد منتخب کریں",
    description: "تفصیل",
    enterDescription: "تفصیل درج کریں",
    subject: "مضمون",
    pleaseEnterSubject: "براہ کرم موضوع درج کریں",
    customApprovals: "حسب ضرورت منظوری",
    createdByMe: "میرے ذریعہ تخلیق کردہ",
    list: "فہرست",
    table: "ٹیبل",
    referenceNo: "حوالہ نمبر",
    creator: "خالق",
    status: "حالت",
    date: "تاریخ",

    loanPurpose: {
      vehicle: "گاڑی",
      personal: "ذاتی",
      wedding: "شادی",
      medical: "طبی",
      education: "تعلیم",
      house: "گھر",
      other: "دوسرے",
    },
  },
  /*** Define language write side ***/
  Direction: "rtl",
};
export default urdu;
