const en = {
  warningDictionary: {
    filter: "Filter",
    selectApprovers: "Select Approvers",
    warning: "Warnings",
    createdByMe:"created By Me",
    create: "Create Warning",
    upload: "Upload",
    tableView: "Table View",
    listView: "List View",
    list:"List",
    table:"Table",
    selectMember: "Select Members",
    members: "Members",
    category: "Category",
    approvers: "Approvers",
    warningTo: "Warning To",
    myWarning: "My Warning",
    warningToMe: "Warning To Me",
    createWarning: "Create Warning",
    forApproval: "For Approval",
    deductionPerMonth: "Deduction/Months",
    pleaseEnterloanTenureInMonths: "Please enter loan tenure",
    amount: "Amount",
    pleaseEnterAmount: "Please enter amount",
    purpose: "Purpose",
    selectPurpose: "Select purpose",
    deadline: "Deadline",
    description: "Description",
    enterDescription: "Enter Description",
    warningCategory: "Warning Category",
    enterwarningCategory: "Enter Warning Category",
    addCategory: "Add Category",
    saveCategory: "Save category",
    clear: "Clear",
    name: "Name",
    loanPurpose: {
      vehicle: "Vehicle",
      personal: "Personal",
      wedding: "Wedding",
      medical: "Medical",
      education: "Education",
      house: "House",
      other: "Other",
    },
    tables: {
      sort:"sort",
			ReferenceNum:"Reference Number",
      Creator:"Creator",
      Status:"Status",
      Category:"Category",
      warningTo:"Warning To",
      Date:"Date",
      Approvers:"Approvers",
		},
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default en;
