const hindi = {
  warningDictionary: {
    filter: "फ़िल्टर",
    selectApprovers: "अनुमोदकों का चयन करें",
    warning: "चेतावनी",
    create: "बनाएं",
    upload: "अपलोड करें",
    tableView: "तालिका दृश्य",
    listView: "सूची देखें",
    selectMember: "सदस्य चुनें",
    members: "सदस्य",
    category: "श्रेणी",
    approvers: "अनुमोदकों का चयन करें0",
    warningTo: "अनुमोदकों का चयन करें1",
    myWarning: "अनुमोदकों का चयन करें2",
    warningToMe: "अनुमोदकों का चयन करें3",
    createWarning: "अनुमोदकों का चयन करें4",
    forApproval: "अनुमोदकों का चयन करें5",
    deductionPerMonth: "अनुमोदकों का चयन करें6",
    pleaseEnterloanTenureInMonths: "अनुमोदकों का चयन करें7",
    amount: "अनुमोदकों का चयन करें8",
    pleaseEnterAmount: "अनुमोदकों का चयन करें9",
    purpose: "चेतावनी0",
    selectPurpose: "चेतावनी1",
    deadline: "चेतावनी2",
    description: "चेतावनी3",
    enterDescription: "चेतावनी4",
    loanPurpose: {
      vehicle: "चेतावनी5",
      personal: "चेतावनी6",
      wedding: "चेतावनी7",
      medical: "चेतावनी8",
      education: "चेतावनी9",
      house: "बनाएं0",
      other: "बनाएं1",
    },
  },

  /*** Define language write side ***/
  Direction: "ltr",
};
export default hindi;
