const urdu = {
  warningDictionary: {
    filter: "فلٹر",
    selectApprovers: "منظور کنندگان کو منتخب کریں۔",
    warning: "انتباہ",
    create: "بنانا",
    createdByMe:"میری طرف سے پیدا کیا",
    upload: "اپ لوڈ",
    tableView: "میز کا منظر",
    listView: "فہرست دیکھیں",
    list:"فہرست",
    table:"ٹیبل",
    selectMember: "ممبر کو منتخب کریں۔",
    members: "اراکین",
    category: "قسم",
    approvers: "منظوری دینے والے",
    warningTo: "کو انتباہ",
    myWarning: "میرا انتباہ",
    warningToMe: "مجھے انتباہ",
    createWarning: "انتباہ بنائیں",
    forApproval: "منظوری کے لیے",
    deductionPerMonth: "مہینے/کٹوتی",
    pleaseEnterloanTenureInMonths: "براہ کرم قرض کی مدت درج کریں",
    amount: "رقم",
    pleaseEnterAmount: "براہ کرم رقم درج کریں",
    deadline: "ڈیڈ لائن",
    purpose: "مقصد",
    selectPurpose: "مقصد منتخب کریں",
    description: "تفصیل",
    enterDescription: "تفصیل درج کریں",
    warningCategory: "انتباہی زمرہ",
    enterwarningCategory: "انتباہی زمرہ درج کریں",
    addCategory: "زمرہ شامل کریں",
    saveCategory: "زمرہ محفوظ کریں",
    clear: "صاف",
    name: "نام",
    loanPurpose: {
      vehicle: "گاڑی",
      personal: "ذاتی",
      wedding: "شادی",
      medical: "طبی",
      education: "تعلیم",
      house: "گھر",
      other: "دوسرے",
    },
    tables: {
      sort:"ترتیب دیں",
			ReferenceNum:"حوالہ نمبر",
      Creator:"خالق",
      Status:"حالت",
      warningTo:"وارننگ ٹو",
      Category:"قسم",
      Date:"تاریخ",
      Approvers:"منظور کرنے والے",
		},
  },
  /*** Define language write side ***/
  Direction: "rtl",
};
export default urdu;
